import { Category, Test } from '@/types';

// 카테고리 데이터
export const categories: Category[] = [
  {
    id: 'personality',
    name: '성격 테스트',
    slug: 'personality',
    icon: 'Brain',
    description: 'MBTI, 성격 유형 등 나의 성격을 알아보는 테스트',
  },
  {
    id: 'psychology',
    name: '심리 테스트',
    slug: 'psychology',
    icon: 'Heart',
    description: '심층 심리, 무의식을 탐구하는 테스트',
  },
  {
    id: 'relationship',
    name: '연애/관계',
    slug: 'relationship',
    icon: 'Users',
    description: '연애 스타일, 궁합, 관계 성향 테스트',
  },
  {
    id: 'career',
    name: '적성/직업',
    slug: 'career',
    icon: 'Briefcase',
    description: '직업 적성, 커리어 방향성 테스트',
  },
  {
    id: 'fun',
    name: '재미/운세',
    slug: 'fun',
    icon: 'Sparkles',
    description: '가볍게 즐기는 재미있는 테스트',
  },
  {
    id: 'iq',
    name: 'IQ/두뇌',
    slug: 'iq',
    icon: 'Lightbulb',
    description: 'IQ 테스트, 논리력, 두뇌 게임',
  },
];

// 테스트 데이터
export const tests: Test[] = [
  // 성격 테스트
  {
    id: 'mbti-basic',
    title: 'MBTI 성격 유형 테스트',
    slug: 'mbti-basic',
    description: '16가지 성격 유형 중 나는 어떤 유형일까요? AI가 분석하는 정밀 MBTI 테스트로 나의 성격을 깊이 있게 알아보세요.',
    shortDescription: 'AI가 분석하는 16가지 성격 유형',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/mbti.png',
    questionCount: 20,
    estimatedTime: 5,
    participantCount: 184520,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '성격', '인기'],
    createdAt: '2024-01-01',
  },
  {
    id: 'soul-animal',
    title: '나의 소울 애니멀 테스트',
    slug: 'soul-animal',
    description: '당신의 영혼을 닮은 동물은 무엇일까요? 성격과 행동 패턴을 분석하여 당신과 가장 닮은 동물을 찾아드립니다.',
    shortDescription: '내 영혼을 닮은 동물 찾기',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/soul-animal.png',
    questionCount: 12,
    estimatedTime: 2,
    participantCount: 127840,
    isPremium: false,
    price: 0,
    tags: ['동물', '성격', '재미'],
    createdAt: '2024-01-15',
  },
  {
    id: 'color-personality',
    title: '컬러로 보는 내 성격',
    slug: 'color-personality',
    description: '색채 심리학을 기반으로 당신의 성격을 분석합니다. 당신을 대표하는 색은 무엇일까요? 8가지 색깔 중 나의 성격 컬러를 찾아보세요.',
    shortDescription: '나를 대표하는 색깔 찾기',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/color.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 98450,
    isPremium: false,
    price: 0,
    tags: ['색깔', '심리', '감성'],
    createdAt: '2024-02-01',
  },

  // 심리 테스트
  {
    id: 'stress-level',
    title: '스트레스 지수 측정',
    slug: 'stress-level',
    description: '현재 당신의 스트레스 수준은 어느 정도일까요? 정신건강 전문가가 설계한 테스트로 확인해보세요.',
    shortDescription: '나의 스트레스 레벨 체크',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/stress.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 76890,
    isPremium: false,
    price: 0,
    tags: ['스트레스', '정신건강', '자가진단'],
    createdAt: '2024-01-20',
  },
  {
    id: 'attachment-style',
    title: '애착 유형 테스트',
    slug: 'attachment-style',
    description: '관계에서 나는 어떤 애착 유형을 보일까요? 안정형, 불안형, 회피형 중 나의 유형을 알아보세요.',
    shortDescription: '나의 애착 유형 분석',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/attachment.png',
    questionCount: 18,
    estimatedTime: 4,
    participantCount: 52340,
    isPremium: true,
    price: 1000,
    tags: ['애착', '관계', '심층분석'],
    createdAt: '2024-02-10',
  },

  // 연애/관계
  {
    id: 'love-language',
    title: '5가지 사랑의 언어 테스트',
    slug: 'love-language',
    description: '당신이 사랑을 표현하고 느끼는 방식은? 5가지 사랑의 언어 중 나의 유형을 찾아보세요.',
    shortDescription: '나의 사랑 표현 방식',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/love-language.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 143670,
    isPremium: false,
    price: 0,
    tags: ['연애', '사랑', '커플'],
    createdAt: '2024-01-25',
  },
  {
    id: 'ideal-type',
    title: 'AI가 분석하는 이상형 테스트',
    slug: 'ideal-type',
    description: 'AI가 당신의 무의식을 분석하여 진짜 이상형을 찾아드립니다.',
    shortDescription: '숨겨진 진짜 이상형 찾기',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/ideal-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 167230,
    isPremium: false,
    price: 0,
    tags: ['이상형', '연애', 'AI'],
    createdAt: '2024-02-05',
  },
  {
    id: 'dating-style',
    title: '연애 성향 테스트',
    slug: 'dating-style',
    description: '당신의 연애 스타일은? 올인형, 밀당형, 친구형 등 6가지 연애 성향 중 나의 유형을 알아보세요.',
    shortDescription: '나의 연애 스타일 분석',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/dating-style.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 89560,
    isPremium: false,
    price: 0,
    tags: ['연애', '성향', '스타일'],
    createdAt: '2024-02-20',
  },
  {
    id: 'love-charm',
    title: '나의 연애 매력 포인트',
    slug: 'love-charm',
    description: '이성에게 어필하는 나만의 매력 포인트는? 귀여움, 섹시함, 지적 매력 등 6가지 매력 유형을 분석합니다.',
    shortDescription: '나의 연애 매력 분석',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/love-charm.png',
    questionCount: 12,
    estimatedTime: 2,
    participantCount: 76890,
    isPremium: false,
    price: 0,
    tags: ['연애', '매력', '어필'],
    createdAt: '2024-02-22',
  },
  {
    id: 'push-pull',
    title: '밀당 능력 테스트',
    slug: 'push-pull',
    description: '연애에서 밀고 당기기, 나는 얼마나 잘할까? 직진러버부터 밀당 마스터까지 당신의 밀당 능력을 측정합니다.',
    shortDescription: '나의 밀당 능력 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/push-pull.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58340,
    isPremium: false,
    price: 0,
    tags: ['밀당', '연애', '썸', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'breakup-recovery',
    title: '이별 회복 단계 테스트',
    slug: 'breakup-recovery',
    description: '이별 후 지금 당신은 어느 단계에 있나요? 부정, 분노, 협상, 우울, 수용... 당신의 회복 단계를 알아봅니다.',
    shortDescription: '나의 이별 극복 단계는?',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/breakup-recovery.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['이별', '회복', '연애', '심리'],
    createdAt: '2024-11-26',
  },
  {
    id: 'company-dinner',
    title: '회식 유형 테스트',
    slug: 'company-dinner',
    description: '회식에서 당신은 어떤 캐릭터? 분위기 메이커부터 탈출 전문가까지, 나의 회식 스타일을 알아봅니다.',
    shortDescription: '회식에서 나는 어떤 유형?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/company-dinner.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 45670,
    isPremium: false,
    price: 0,
    tags: ['회식', '직장', '유머', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'drama-character',
    title: '드라마 캐릭터 테스트',
    slug: 'drama-character',
    description: '드라마에서 당신은 어떤 캐릭터? 메인 주인공부터 씬스틸러 코믹까지, 당신의 드라마 캐릭터를 알아봅니다.',
    shortDescription: '드라마에서 나는 어떤 역할?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/drama-character.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 78230,
    isPremium: false,
    price: 0,
    tags: ['드라마', '캐릭터', '유머', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'perfectionism',
    title: '완벽주의 테스트',
    slug: 'perfectionism',
    description: '당신의 완벽주의 성향은 어느 정도? 여유로운 낙천가부터 극단적 완벽주의자까지, 나의 완벽주의 레벨을 측정합니다.',
    shortDescription: '나의 완벽주의 레벨은?',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/perfectionism.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 56780,
    isPremium: false,
    price: 0,
    tags: ['완벽주의', '심리', '자기이해', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'empathy-level',
    title: '공감 능력 테스트',
    slug: 'empathy-level',
    description: '당신의 공감 능력은 어느 정도? 이성적 분석가부터 고감도 엠파스까지, 나의 공감 레벨을 측정합니다.',
    shortDescription: '나의 공감 능력 측정',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/empathy-level.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 63450,
    isPremium: false,
    price: 0,
    tags: ['공감', '심리', 'EQ', '바이럴'],
    createdAt: '2024-11-26',
  },

  // 적성/직업
  {
    id: 'career-aptitude',
    title: '직업 적성 검사',
    slug: 'career-aptitude',
    description: '나에게 맞는 직업은 무엇일까요? 흥미, 성격, 능력을 종합 분석하여 최적의 직업군을 추천해드립니다.',
    shortDescription: '나에게 맞는 직업 찾기',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/career.png',
    questionCount: 20,
    estimatedTime: 5,
    participantCount: 68450,
    isPremium: true,
    price: 1000,
    tags: ['직업', '적성', '진로'],
    createdAt: '2024-01-30',
  },
  {
    id: 'work-style',
    title: '업무 스타일 테스트',
    slug: 'work-style',
    description: '당신의 업무 스타일은? 협업형, 독립형, 리더형 등 나의 업무 성향을 알아보세요.',
    shortDescription: '나의 일하는 스타일 분석',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/work-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 54320,
    isPremium: false,
    price: 0,
    tags: ['업무', '직장', '협업'],
    createdAt: '2024-02-15',
  },
  {
    id: 'money-sense',
    title: '금전 감각 테스트',
    slug: 'money-sense',
    description: '당신의 금전 감각은 어떤 유형일까요? 저축형, 소비형, 투자형 등 6가지 금전 유형을 분석합니다.',
    shortDescription: '나의 금전 감각 분석',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/money-sense.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 65430,
    isPremium: false,
    price: 0,
    tags: ['금전', '재테크', '소비'],
    createdAt: '2024-02-25',
  },
  {
    id: 'rich-mindset',
    title: '부자 마인드 테스트',
    slug: 'rich-mindset',
    description: '당신은 부자가 될 마인드셋을 가지고 있나요? 부자들의 사고방식과 얼마나 일치하는지 측정합니다.',
    shortDescription: '부자 잠재력 측정',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/rich-mindset.png',
    questionCount: 15,
    estimatedTime: 4,
    participantCount: 58970,
    isPremium: false,
    price: 0,
    tags: ['부자', '마인드', '재테크'],
    createdAt: '2024-02-28',
  },

  // 재미/운세
  {
    id: 'past-life',
    title: '전생 테스트',
    slug: 'past-life',
    description: '당신의 전생은 어떤 모습이었을까요? 재미로 알아보는 전생 이야기!',
    shortDescription: '나의 전생 알아보기',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/past-life.png',
    questionCount: 10,
    estimatedTime: 2,
    participantCount: 195670,
    isPremium: false,
    price: 0,
    tags: ['전생', '재미', '운세'],
    createdAt: '2024-01-10',
  },
  {
    id: 'luck-2025',
    title: '2025년 운세 테스트',
    slug: 'luck-2025',
    description: '2025년 당신의 운세는? AI가 분석하는 새해 운세를 확인해보세요.',
    shortDescription: '2025년 나의 운세 보기',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/luck-2025.png',
    questionCount: 10,
    estimatedTime: 2,
    participantCount: 112340,
    isPremium: false,
    price: 0,
    tags: ['운세', '2025', '새해'],
    createdAt: '2024-12-01',
  },

  // IQ/두뇌
  {
    id: 'iq-test',
    title: 'IQ 테스트',
    slug: 'iq-test',
    description: '당신의 IQ는 몇일까요? 논리력, 공간지각력, 언어능력을 종합 측정합니다.',
    shortDescription: '나의 IQ 측정하기',
    categoryId: 'iq',
    thumbnailUrl: '/images/tests/iq.png',
    questionCount: 25,
    estimatedTime: 10,
    participantCount: 87650,
    isPremium: true,
    price: 1000,
    tags: ['IQ', '지능', '두뇌'],
    createdAt: '2024-02-01',
  },
  {
    id: 'brain-type',
    title: '좌뇌 우뇌 테스트',
    slug: 'brain-type',
    description: '당신은 좌뇌형? 우뇌형? 논리적인 좌뇌와 창의적인 우뇌 중 어느 쪽이 더 발달했는지 알아보세요.',
    shortDescription: '좌뇌 vs 우뇌 유형 분석',
    categoryId: 'iq',
    thumbnailUrl: '/images/tests/brain-type.png',
    questionCount: 12,
    estimatedTime: 2,
    participantCount: 73450,
    isPremium: false,
    price: 0,
    tags: ['좌뇌', '우뇌', '두뇌'],
    createdAt: '2024-02-08',
  },
  {
    id: 'disc-personality',
    title: 'DISC 성격 유형 테스트',
    slug: 'disc-personality',
    description: '당신의 행동 유형은? 주도형(D), 사교형(I), 안정형(S), 신중형(C) 중 나의 DISC 유형을 알아보세요.',
    shortDescription: 'DISC 행동 유형 분석',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/disc.png',
    questionCount: 20,
    estimatedTime: 4,
    participantCount: 45670,
    isPremium: false,
    price: 0,
    tags: ['DISC', '성격', '행동'],
    createdAt: '2024-03-01',
  },
  {
    id: 'enneagram',
    title: '에니어그램 테스트',
    slug: 'enneagram',
    description: '9가지 성격 유형 중 나는 어떤 유형일까요? 에니어그램으로 깊이 있는 자기 이해를 시작하세요.',
    shortDescription: '9가지 에니어그램 유형 분석',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/enneagram.png',
    questionCount: 27,
    estimatedTime: 5,
    participantCount: 38920,
    isPremium: false,
    price: 0,
    tags: ['에니어그램', '성격', '자기이해'],
    createdAt: '2024-03-05',
  },
  {
    id: 'eq-test',
    title: 'EQ 감성지능 테스트',
    slug: 'eq-test',
    description: '당신의 감성지능은 얼마나 높을까요? 자기인식, 자기조절, 공감능력 등 EQ를 종합 측정합니다.',
    shortDescription: '나의 감성지능 측정',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/eq.png',
    questionCount: 20,
    estimatedTime: 4,
    participantCount: 42350,
    isPremium: false,
    price: 0,
    tags: ['EQ', '감성지능', '공감'],
    createdAt: '2024-03-10',
  },
  {
    id: 'mental-strength',
    title: '멘탈 강도 테스트',
    slug: 'mental-strength',
    description: '당신의 멘탈은 얼마나 강할까요? 스트레스 대처력, 회복탄력성, 감정 조절력을 종합 분석합니다.',
    shortDescription: '나의 멘탈 강도 측정',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/mental-strength.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 36780,
    isPremium: false,
    price: 0,
    tags: ['멘탈', '회복탄력성', '정신건강'],
    createdAt: '2024-03-15',
  },
  {
    id: 'burnout-level',
    title: '번아웃 지수 테스트',
    slug: 'burnout-level',
    description: '지금 당신은 번아웃 상태일까요? 신체적, 정서적 소진 정도를 측정하고 회복 방법을 알아보세요.',
    shortDescription: '나의 번아웃 상태 체크',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/burnout.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 31450,
    isPremium: false,
    price: 0,
    tags: ['번아웃', '직장', '스트레스'],
    createdAt: '2024-03-20',
  },
  {
    id: 'focus-test',
    title: '집중력 테스트',
    slug: 'focus-test',
    description: '당신의 집중력은 어느 정도일까요? 집중력 유형을 분석하고 향상 방법을 알려드립니다.',
    shortDescription: '나의 집중력 수준 측정',
    categoryId: 'iq',
    thumbnailUrl: '/images/tests/focus.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 28930,
    isPremium: false,
    price: 0,
    tags: ['집중력', '두뇌', '생산성'],
    createdAt: '2024-03-25',
  },
  {
    id: 'dark-triad',
    title: '다크 트라이어드 테스트',
    slug: 'dark-triad',
    description: '나르시시즘, 마키아벨리즘, 사이코패시 - 당신의 어두운 면은 어떤 모습일까요? 심리학적으로 검증된 다크 트라이어드 테스트로 숨겨진 성격을 분석합니다.',
    shortDescription: '나의 어두운 성격 분석',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/dark-triad.png',
    questionCount: 18,
    estimatedTime: 4,
    participantCount: 45230,
    isPremium: false,
    price: 0,
    tags: ['다크 트라이어드', '나르시시즘', '심리', '바이럴'],
    createdAt: '2024-04-01',
  },
  {
    id: 'mental-age',
    title: '나의 정신연령 테스트',
    slug: 'mental-age',
    description: '실제 나이와 정신 나이는 다를 수 있어요! 당신의 생각, 행동, 가치관을 분석하여 진짜 정신연령을 알려드립니다.',
    shortDescription: '내 진짜 정신연령은?',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/mental-age.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['정신연령', '심리', '재미', '바이럴'],
    createdAt: '2024-04-05',
  },
  {
    id: 'hidden-talent',
    title: '나의 숨겨진 재능 테스트',
    slug: 'hidden-talent',
    description: '나도 몰랐던 잠재력을 발견하세요! 당신의 행동 패턴과 성향을 분석하여 숨겨진 재능과 적합한 분야를 알려드립니다.',
    shortDescription: '나도 몰랐던 잠재력 발견',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/hidden-talent.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 52340,
    isPremium: false,
    price: 0,
    tags: ['재능', '적성', '잠재력', '바이럴'],
    createdAt: '2024-04-10',
  },
  {
    id: 'communication-style',
    title: '의사소통 스타일 테스트',
    slug: 'communication-style',
    description: '당신의 대화 스타일은 어떤 유형일까요? 직설적? 외교적? 당신만의 소통 방식을 분석하고 더 효과적인 커뮤니케이션 팁을 알려드립니다.',
    shortDescription: '나의 소통 스타일 분석',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/communication-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 41250,
    isPremium: false,
    price: 0,
    tags: ['소통', '대화', '관계', '바이럴'],
    createdAt: '2024-04-12',
  },
  {
    id: 'leadership-type',
    title: '리더십 유형 테스트',
    slug: 'leadership-type',
    description: '당신은 어떤 유형의 리더일까요? 비저너리, 민주형, 분석형, 코칭형 중 당신의 리더십 스타일을 알아보세요.',
    shortDescription: '나의 리더십 스타일 분석',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/leadership-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 38920,
    isPremium: false,
    price: 0,
    tags: ['리더십', '직장', '커리어', '바이럴'],
    createdAt: '2024-04-15',
  },
  {
    id: 'creativity-index',
    title: '창의력 지수 테스트',
    slug: 'creativity-index',
    description: '당신의 창의력은 몇 점일까요? 상상력, 독창성, 유연성을 분석하여 창의력 지수를 측정하고 개발 방법을 알려드립니다.',
    shortDescription: '나의 창의력 지수 측정',
    categoryId: 'iq',
    thumbnailUrl: '/images/tests/creativity-index.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 45670,
    isPremium: false,
    price: 0,
    tags: ['창의력', '상상력', '두뇌', '바이럴'],
    createdAt: '2024-04-18',
  },
  {
    id: 'inner-child',
    title: '내면아이 테스트',
    slug: 'inner-child',
    description: '당신 안에 살고 있는 어린 나는 어떤 아이일까요? 내면아이를 만나고 치유하는 여정을 시작해보세요.',
    shortDescription: '내 안의 어린 나 만나기',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/inner-child.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 34560,
    isPremium: false,
    price: 0,
    tags: ['내면아이', '심리', '치유', '바이럴'],
    createdAt: '2024-04-20',
  },
  {
    id: 'flex-tendency',
    title: '플렉스 성향 테스트',
    slug: 'flex-tendency',
    description: '당신의 소비/과시 성향은 어떤 유형일까요? 경험파? 명품파? 저축파? 소셜파? 당신만의 플렉스 스타일을 알아보세요.',
    shortDescription: '나의 플렉스 스타일 분석',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/flex-tendency.png',
    questionCount: 12,
    estimatedTime: 2,
    participantCount: 56780,
    isPremium: false,
    price: 0,
    tags: ['플렉스', '소비', '재미', '바이럴'],
    createdAt: '2024-04-22',
  },
  {
    id: 'emotion-regulation',
    title: '감정 조절력 테스트',
    slug: 'emotion-regulation',
    description: '당신의 감정 관리 능력은 어느 정도일까요? 감정 조절력을 측정하고 더 나은 감정 관리법을 알아보세요.',
    shortDescription: '나의 감정 조절 능력 측정',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/emotion-regulation.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 41230,
    isPremium: false,
    price: 0,
    tags: ['감정', '심리', '자기관리', '바이럴'],
    createdAt: '2024-04-25',
  },
  {
    id: 'mbti-compatibility',
    title: 'MBTI 궁합 테스트',
    slug: 'mbti-compatibility',
    description: '나와 상대방의 MBTI 궁합은 몇 점일까요? 연인, 친구, 동료와의 궁합을 확인하고 관계 개선 팁을 알아보세요.',
    shortDescription: 'MBTI로 보는 우리 궁합',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/mbti-compatibility.png',
    questionCount: 5,
    estimatedTime: 2,
    participantCount: 89340,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '궁합', '연애', '바이럴'],
    createdAt: '2024-04-28',
  },
  {
    id: 'jealousy-type',
    title: '질투 유형 테스트',
    slug: 'jealousy-type',
    description: '연애에서 당신의 질투 성향은? 소유욕형, 탐정형, 속앓이형, 쿨내진동형 중 나의 질투 유형을 알아보세요.',
    shortDescription: '나의 연애 질투 스타일',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/jealousy-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['질투', '연애', '심리', '바이럴'],
    createdAt: '2024-04-30',
  },
  {
    id: 'self-esteem',
    title: '자존감 테스트',
    slug: 'self-esteem',
    description: '당신의 자존감 수준은 어떤가요? 자존감 부자부터 회복이 필요한 단계까지, 나의 자존감을 정확히 측정해보세요.',
    shortDescription: '나의 자존감 레벨 측정',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/self-esteem.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 58760,
    isPremium: false,
    price: 0,
    tags: ['자존감', '심리', '자기이해', '바이럴'],
    createdAt: '2024-05-02',
  },
  {
    id: 'villain-hero',
    title: '빌런 vs 히어로 테스트',
    slug: 'villain-hero',
    description: '당신은 정의의 영웅일까요, 세상을 지배할 빌런일까요? 선과 악의 성향을 분석하여 당신의 진짜 정체를 알려드립니다.',
    shortDescription: '나는 영웅? 악당?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/villain-hero.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72450,
    isPremium: false,
    price: 0,
    tags: ['빌런', '히어로', '재미', '바이럴'],
    createdAt: '2024-05-05',
  },
  {
    id: 'flirting-style',
    title: '썸 스타일 테스트',
    slug: 'flirting-style',
    description: '썸 탈 때 당신의 스타일은? 직진형, 밀당형, 수동형, 친구형 중 나의 썸 스타일을 분석합니다.',
    shortDescription: '썸 탈 때 나의 유형',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/flirting-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 63210,
    isPremium: false,
    price: 0,
    tags: ['썸', '연애', '스타일', '바이럴'],
    createdAt: '2024-05-08',
  },
  {
    id: 't-power',
    title: '전투력 테스트',
    slug: 't-power',
    description: '당신의 사회 생존력/전투력은 몇 점일까요? 멘탈, 체력, 추진력, 목표의식을 종합 분석하여 전투력을 측정합니다.',
    shortDescription: '나의 사회 전투력 측정',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/t-power.png',
    questionCount: 15,
    estimatedTime: 3,
    participantCount: 81230,
    isPremium: false,
    price: 0,
    tags: ['전투력', '멘탈', '재미', '바이럴'],
    createdAt: '2024-05-10',
  },
  {
    id: 'social-battery',
    title: '소셜 배터리 테스트',
    slug: 'social-battery',
    description: '당신의 소셜 배터리는 어느 정도일까요? 사람 만나면 충전되는 타입인지, 방전되는 타입인지 알아보세요.',
    shortDescription: '나의 사회적 에너지 측정',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/social-battery.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 74560,
    isPremium: false,
    price: 0,
    tags: ['소셜배터리', '내향', '외향', '바이럴'],
    createdAt: '2024-05-12',
  },
  {
    id: 'anger-style',
    title: '분노 스타일 테스트',
    slug: 'anger-style',
    description: '화가 날 때 당신은 어떤 유형인가요? 폭발형, 수동공격형, 이성형, 억압형 중 나의 분노 스타일을 알아보세요.',
    shortDescription: '화날 때 나의 유형',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/anger-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48230,
    isPremium: false,
    price: 0,
    tags: ['분노', '감정', '심리', '바이럴'],
    createdAt: '2024-05-15',
  },
  {
    id: 'anxiety-level',
    title: '불안 지수 테스트',
    slug: 'anxiety-level',
    description: '현재 당신의 불안 수준은 어느 정도일까요? 불안의 정도와 원인을 분석하고 관리 방법을 알려드립니다.',
    shortDescription: '나의 불안 레벨 체크',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/anxiety-level.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 52340,
    isPremium: false,
    price: 0,
    tags: ['불안', '정신건강', '심리', '바이럴'],
    createdAt: '2024-05-18',
  },
  {
    id: 'conflict-style',
    title: '갈등 대처 스타일 테스트',
    slug: 'conflict-style',
    description: '갈등 상황에서 당신은 어떻게 대처하나요? 경쟁형, 회피형, 타협형, 협력형 중 나의 유형을 알아보세요.',
    shortDescription: '갈등 상황 대처 유형',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/conflict-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 39870,
    isPremium: false,
    price: 0,
    tags: ['갈등', '대인관계', '심리', '바이럴'],
    createdAt: '2024-05-20',
  },
  {
    id: 'combat-power',
    title: '전투력 측정 테스트',
    slug: 'combat-power',
    description: '당신의 실제 전투력은 몇 점일까요? 체력, 멘탈, 실전 능력을 종합 분석하여 전투력을 측정합니다.',
    shortDescription: '나의 실제 전투력 측정',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/combat-power.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['전투력', '체력', '재미', '바이럴'],
    createdAt: '2024-05-22',
  },
  {
    id: 'decision-style',
    title: '의사결정 스타일 테스트',
    slug: 'decision-style',
    description: '결정을 내릴 때 당신은 어떤 유형인가요? 직감형, 분석형, 의존형, 회피형 중 나의 스타일을 알아보세요.',
    shortDescription: '나의 결정 방식 분석',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/decision-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 41230,
    isPremium: false,
    price: 0,
    tags: ['의사결정', '성격', '심리', '바이럴'],
    createdAt: '2024-05-25',
  },
  {
    id: 'drinking-style',
    title: '술자리 유형 테스트',
    slug: 'drinking-style',
    description: '술 마시면 당신은 어떤 타입? 파티 애니멀, 소셜 드링커, 감성 드링커 중 나의 술자리 유형을 알아보세요.',
    shortDescription: '술자리에서 나의 유형',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/drinking-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58760,
    isPremium: false,
    price: 0,
    tags: ['술자리', '유머', '재미', '바이럴'],
    createdAt: '2024-05-28',
  },
  {
    id: 'first-impression',
    title: '첫인상 테스트',
    slug: 'first-impression',
    description: '사람들이 보는 당신의 첫인상은? 따뜻한, 시크한, 편안한, 수줍은 인상 중 나의 유형을 알아보세요.',
    shortDescription: '나의 첫인상 분석',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/first-impression.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 45670,
    isPremium: false,
    price: 0,
    tags: ['첫인상', '이미지', '성격', '바이럴'],
    createdAt: '2024-06-01',
  },
  {
    id: 'friendship-style',
    title: '우정 스타일 테스트',
    slug: 'friendship-style',
    description: '친구 관계에서 당신은 어떤 유형? 조언자, 경청자, 응원형, 의리파 중 나의 우정 스타일을 알아보세요.',
    shortDescription: '친구로서 나의 유형',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/friendship-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 39560,
    isPremium: false,
    price: 0,
    tags: ['우정', '친구', '관계', '바이럴'],
    createdAt: '2024-06-05',
  },
  {
    id: 'gaslighting-check',
    title: '가스라이팅 체크 테스트',
    slug: 'gaslighting-check',
    description: '혹시 가스라이팅 당하고 있나요? 관계에서 나타나는 조작적 패턴을 체크하고 건강한 관계를 위한 조언을 드립니다.',
    shortDescription: '관계 건강성 체크',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/gaslighting-check.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 43210,
    isPremium: false,
    price: 0,
    tags: ['가스라이팅', '관계', '심리', '바이럴'],
    createdAt: '2024-06-08',
  },
  {
    id: 'humor-type',
    title: '유머 유형 테스트',
    slug: 'humor-type',
    description: '당신의 웃음 포인트는? 언어유희형, 몸개그형, 자학개그형, 블랙코미디형 중 나의 유머 스타일을 알아보세요.',
    shortDescription: '나의 유머 스타일 분석',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/humor-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 51230,
    isPremium: false,
    price: 0,
    tags: ['유머', '개그', '재미', '바이럴'],
    createdAt: '2024-06-10',
  },
  {
    id: 'introvert-extrovert',
    title: '내향/외향 테스트',
    slug: 'introvert-extrovert',
    description: '당신은 내향인? 외향인? 양향인? 에너지를 얻는 방식과 사회적 성향을 분석하여 정확한 유형을 알려드립니다.',
    shortDescription: '내향인 vs 외향인',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/introvert-extrovert.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 62340,
    isPremium: false,
    price: 0,
    tags: ['내향', '외향', '성격', '바이럴'],
    createdAt: '2024-06-12',
  },
  {
    id: 'life-graph',
    title: '인생 그래프 테스트',
    slug: 'life-graph',
    description: '당신의 인생 패턴은? 상승형, 파도형, 고원형 등 인생 그래프를 분석하고 미래를 예측해보세요.',
    shortDescription: '나의 인생 패턴 분석',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/life-graph.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 47890,
    isPremium: false,
    price: 0,
    tags: ['인생', '운세', '재미', '바이럴'],
    createdAt: '2024-06-15',
  },
  {
    id: 'love-trauma',
    title: '연애 트라우마 테스트',
    slug: 'love-trauma',
    description: '과거 연애가 남긴 상처는? 연애 트라우마 정도를 체크하고 치유를 위한 조언을 드립니다.',
    shortDescription: '연애 상처 체크',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/love-trauma.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 38920,
    isPremium: false,
    price: 0,
    tags: ['연애', '트라우마', '심리', '바이럴'],
    createdAt: '2024-06-18',
  },
  {
    id: 'people-pleaser',
    title: '피플플리저 테스트',
    slug: 'people-pleaser',
    description: '나는 남의 눈치를 얼마나 볼까요? 피플플리저 성향을 체크하고 건강한 경계를 세우는 방법을 알아보세요.',
    shortDescription: '눈치 보기 성향 체크',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/people-pleaser.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 42150,
    isPremium: false,
    price: 0,
    tags: ['피플플리저', '눈치', '심리', '바이럴'],
    createdAt: '2024-06-20',
  },
  {
    id: 'personality-duality',
    title: '이중 인격 테스트',
    slug: 'personality-duality',
    description: '혼자 있을 때와 사람들 앞에서 나는 얼마나 다를까요? 공적 자아와 사적 자아의 갭을 분석합니다.',
    shortDescription: '밖에서 vs 집에서 나',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/personality-duality.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 53670,
    isPremium: false,
    price: 0,
    tags: ['이중인격', '페르소나', '성격', '바이럴'],
    createdAt: '2024-06-22',
  },
  {
    id: 'procrastination',
    title: '미루기 테스트',
    slug: 'procrastination',
    description: '당신의 미루기 레벨은? 실행력 만렙부터 프로 미루기꾼까지, 미루기 성향을 분석하고 극복 방법을 알려드립니다.',
    shortDescription: '나의 미루기 레벨 측정',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/procrastination.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 61230,
    isPremium: false,
    price: 0,
    tags: ['미루기', '습관', '심리', '바이럴'],
    createdAt: '2024-06-25',
  },
  {
    id: 'sleep-type',
    title: '수면 유형 테스트',
    slug: 'sleep-type',
    description: '당신의 수면 패턴은? 얼리버드, 올빼미형, 불규칙형 등 수면 유형을 분석하고 최적의 수면 스케줄을 알려드립니다.',
    shortDescription: '나의 수면 패턴 분석',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/sleep-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 45670,
    isPremium: false,
    price: 0,
    tags: ['수면', '건강', '생활', '바이럴'],
    createdAt: '2024-06-28',
  },
  {
    id: 'sns-personality',
    title: 'SNS 성격 테스트',
    slug: 'sns-personality',
    description: '당신의 SNS 인격은? 인플루언서형, 관찰자형, 중독형 등 SNS 사용 패턴을 분석합니다.',
    shortDescription: 'SNS에서 나의 모습',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/sns-personality.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58920,
    isPremium: false,
    price: 0,
    tags: ['SNS', '소셜미디어', '재미', '바이럴'],
    createdAt: '2024-07-01',
  },
  {
    id: 'spending-type',
    title: '소비 유형 테스트',
    slug: 'spending-type',
    description: '당신의 소비 패턴은? 저축왕, 계획적 소비자, 충동 소비자 등 나의 소비 유형을 분석합니다.',
    shortDescription: '나의 소비 패턴 분석',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/spending-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 47890,
    isPremium: false,
    price: 0,
    tags: ['소비', '재테크', '돈', '바이럴'],
    createdAt: '2024-07-05',
  },
  {
    id: 'tarot-today',
    title: '오늘의 타로 테스트',
    slug: 'tarot-today',
    description: '오늘 당신에게 필요한 메시지는? 타로 카드가 전하는 오늘의 운세와 조언을 확인해보세요.',
    shortDescription: '오늘의 타로 메시지',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/tarot-today.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72340,
    isPremium: false,
    price: 0,
    tags: ['타로', '운세', '재미', '바이럴'],
    createdAt: '2024-07-08',
  },
  {
    id: 'toxic-check',
    title: '독성 관계 체크 테스트',
    slug: 'toxic-check',
    description: '이 관계, 괜찮은 걸까요? 관계의 건강성을 체크하고 독성 패턴을 확인해보세요.',
    shortDescription: '관계 건강성 체크',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/toxic-check.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 39870,
    isPremium: false,
    price: 0,
    tags: ['관계', '독성', '심리', '바이럴'],
    createdAt: '2024-07-10',
  },
  {
    id: 'trauma-check',
    title: '트라우마 체크 테스트',
    slug: 'trauma-check',
    description: '마음의 상처를 확인해보세요. 트라우마 증상을 체크하고 치유를 위한 조언을 드립니다.',
    shortDescription: '마음의 상처 체크',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/trauma-check.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 35670,
    isPremium: false,
    price: 0,
    tags: ['트라우마', '정신건강', '심리', '바이럴'],
    createdAt: '2024-07-12',
  },
  {
    id: 'ex-attachment',
    title: '전 애인 미련 지수 테스트',
    slug: 'ex-attachment',
    description: '아직 전 애인에게 미련이 남아있나요? 솔직한 질문으로 나의 미련 지수를 측정하고 치유를 위한 조언을 드립니다.',
    shortDescription: '전 애인 미련 지수 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/ex-attachment.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 54320,
    isPremium: false,
    price: 0,
    tags: ['이별', '미련', '전애인', '연애', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'reunion-chance',
    title: '재회 가능성 테스트',
    slug: 'reunion-chance',
    description: '우리 다시 만날 수 있을까? 이별 상황을 분석하여 재회 가능성을 측정하고 현실적인 조언을 드립니다.',
    shortDescription: '재회 가능성 분석',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/reunion-chance.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48760,
    isPremium: false,
    price: 0,
    tags: ['재회', '이별', '연애', '가능성', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'love-cell',
    title: '연애 세포 테스트',
    slug: 'love-cell',
    description: '내 연애 세포는 살아있을까? 연애에 대한 관심도와 준비도를 측정하고 연애 타이밍을 알려드립니다.',
    shortDescription: '연애 세포 활성도 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/love-cell.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 52340,
    isPremium: false,
    price: 0,
    tags: ['연애', '세포', '솔로', '연애준비', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'couple-fight',
    title: '커플 싸움 패턴 테스트',
    slug: 'couple-fight',
    description: '연인과 싸울 때 나는 어떤 유형? 6가지 싸움 패턴을 분석하고 건강한 갈등 해결법을 알려드립니다.',
    shortDescription: '싸움 패턴 분석',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/couple-fight.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 47890,
    isPremium: false,
    price: 0,
    tags: ['커플', '싸움', '갈등', '연애', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'breakup-reason',
    title: '이별 원인 분석 테스트',
    slug: 'breakup-reason',
    description: '왜 헤어지게 됐을까? 이별의 근본 원인을 분석하고 다음 연애를 위한 교훈을 알려드립니다.',
    shortDescription: '이별 원인 분석',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/breakup-reason.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 43560,
    isPremium: false,
    price: 0,
    tags: ['이별', '원인', '연애', '분석', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'next-love-ready',
    title: '다음 연애 준비도 테스트',
    slug: 'next-love-ready',
    description: '새로운 사랑, 준비됐어? 이별 후 회복 상태를 점검하고 새 연애를 시작할 최적의 타이밍을 알려드립니다.',
    shortDescription: '새 연애 준비도 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/next-love-ready.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 45120,
    isPremium: false,
    price: 0,
    tags: ['새연애', '준비', '회복', '솔로', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'love-meter',
    title: '연인 애정도 테스트',
    slug: 'love-meter',
    description: '우리 커플 애정 온도는 몇 도? 연인과의 관계 온도를 측정하고 더 뜨거운 사랑을 위한 조언을 드립니다.',
    shortDescription: '커플 애정 온도 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/love-meter.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58940,
    isPremium: false,
    price: 0,
    tags: ['커플', '애정', '연애', '온도', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'crush-success',
    title: '짝사랑 성공률 테스트',
    slug: 'crush-success',
    description: '이 사랑, 이루어질까? 짝사랑 상대의 신호를 분석하고 성공 확률을 알려드립니다.',
    shortDescription: '짝사랑 성공 확률 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/crush-success.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67230,
    isPremium: false,
    price: 0,
    tags: ['짝사랑', '성공률', '연애', '호감', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'red-flag-detect',
    title: '레드플래그 감별 테스트',
    slug: 'red-flag-detect',
    description: '이 사람, 괜찮은 사람일까? 연애 상대의 위험 신호를 감지하고 건강한 관계를 위한 조언을 드립니다.',
    shortDescription: '연애 위험 신호 감지',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/red-flag-detect.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72450,
    isPremium: false,
    price: 0,
    tags: ['레드플래그', '연애', '위험', '감별', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'confession-timing',
    title: '고백 타이밍 테스트',
    slug: 'confession-timing',
    description: '지금이 고백할 때일까? 상대방과의 관계를 분석하고 최적의 고백 타이밍을 알려드립니다.',
    shortDescription: '고백 타이밍 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/confession-timing.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 54320,
    isPremium: false,
    price: 0,
    tags: ['고백', '타이밍', '연애', '썸', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'friend-to-lover',
    title: '친구→연인 가능성 테스트',
    slug: 'friend-to-lover',
    description: '우리 사이, 친구 이상이 될 수 있을까? 친구와의 관계를 분석하여 연인으로 발전할 가능성을 알려드립니다.',
    shortDescription: '친구에서 연인 가능성 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/friend-to-lover.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48760,
    isPremium: false,
    price: 0,
    tags: ['친구', '연인', '연애', '가능성', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'marriage-fit',
    title: '결혼 적합도 테스트',
    slug: 'marriage-fit',
    description: '우리, 결혼해도 될까? 연인과의 결혼 적합도를 분석하고 행복한 결혼을 위한 조언을 드립니다.',
    shortDescription: '결혼 적합도 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/marriage-fit.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 52340,
    isPremium: false,
    price: 0,
    tags: ['결혼', '적합도', '연애', '커플', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'couple-comm',
    title: '커플 소통 점수 테스트',
    slug: 'couple-comm',
    description: '우리 커플 대화는 몇 점? 연인과의 소통 능력을 측정하고 더 좋은 대화를 위한 팁을 드립니다.',
    shortDescription: '커플 소통 점수 측정',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/couple-comm.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 45890,
    isPremium: false,
    price: 0,
    tags: ['커플', '소통', '대화', '연애', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'dating-pattern',
    title: '연애 패턴 분석 테스트',
    slug: 'dating-pattern',
    description: '내 연애, 왜 맨날 이럴까? 반복되는 연애 패턴을 분석하고 건강한 연애를 위한 조언을 드립니다.',
    shortDescription: '연애 패턴 분석',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/dating-pattern.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58940,
    isPremium: false,
    price: 0,
    tags: ['연애', '패턴', '분석', '심리', '바이럴'],
    createdAt: '2024-11-26',
  },
  // 자극적/바이럴 특화 테스트 (Batch 4)
  {
    id: 'hidden-desire',
    title: '숨겨진 욕망 테스트',
    slug: 'hidden-desire',
    description: '내 무의식 속에 숨겨진 진짜 욕망은 뭘까? 인정받고 싶은지, 자유를 원하는지, 사랑받고 싶은지... 당신의 내면 깊은 곳을 들여다봅니다.',
    shortDescription: '무의식 속 진짜 욕망 탐구',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/hidden-desire.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 45230,
    isPremium: false,
    price: 0,
    tags: ['욕망', '무의식', '심리', '자극적', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'seduction-style',
    title: '유혹 스타일 테스트',
    slug: 'seduction-style',
    description: '당신은 어떤 방식으로 사람을 매료시키나요? 미스터리형, 장난꾸러기형, 지적 매력형... 나만의 유혹 스타일을 알아보세요!',
    shortDescription: '나의 매력 어필 방식',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/seduction-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 52180,
    isPremium: false,
    price: 0,
    tags: ['유혹', '매력', '연애', '자극적', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'true-nature',
    title: '본성 테스트',
    slug: 'true-nature',
    description: '가면 뒤에 숨겨진 진짜 나는 어떤 모습일까? 숨겨진 반항아인지, 통제자인지, 회피자인지... 당신의 진짜 본성을 마주해보세요.',
    shortDescription: '가면 뒤 진짜 나의 모습',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/true-nature.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48760,
    isPremium: false,
    price: 0,
    tags: ['본성', '그림자', '심리', '자극적', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'cheating-risk',
    title: '바람기 지수 테스트',
    slug: 'cheating-risk',
    description: '솔직하게 대답해주세요. 당신의 바람기 지수는 몇 퍼센트일까요? 성자급인지 위험 신호인지, 객관적으로 체크해보세요.',
    shortDescription: '나의 바람기 지수는?',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/cheating-risk.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67340,
    isPremium: false,
    price: 0,
    tags: ['바람기', '연애', '솔직', '자극적', '바이럴'],
    createdAt: '2024-11-26',
  },
  // Batch 5 - 다양성/트렌드 특화 테스트
  {
    id: 'obsession-level',
    title: '집착 레벨 테스트',
    slug: 'obsession-level',
    description: '연애에서 당신의 집착 성향은 어느 정도일까요? 건강한 애착부터 위험한 집착까지, 솔직하게 체크해보세요.',
    shortDescription: '나의 연애 집착 레벨은?',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/obsession-level.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48920,
    isPremium: false,
    price: 0,
    tags: ['집착', '연애', '심리', '자극적', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'gender-identity',
    title: '젠더 정체성 테스트',
    slug: 'gender-identity',
    description: '나의 성 정체성은 어디에 위치할까요? 전통적 남성성/여성성부터 젠더 플루이드까지, 나만의 정체성을 탐색해보세요.',
    shortDescription: '나의 젠더 정체성 탐색',
    categoryId: 'psychology',
    thumbnailUrl: '/images/tests/gender-identity.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 52340,
    isPremium: false,
    price: 0,
    tags: ['젠더', '정체성', '심리', 'MZ', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'youtuber-type',
    title: '유튜버 유형 테스트',
    slug: 'youtuber-type',
    description: '내가 유튜버라면 어떤 콘텐츠를 만들까? 먹방, 게임, 브이로그, 교육... 나에게 맞는 유튜버 유형을 알아보세요!',
    shortDescription: '나의 유튜버 유형은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/youtuber-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['유튜버', '크리에이터', '재미', 'MZ', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'attention-seeker',
    title: '관종력 테스트',
    slug: 'attention-seeker',
    description: '당신의 관심받고 싶은 욕구는 어느 정도일까요? 숨은 은둔자부터 공인 관종까지, 솔직한 관종력을 측정해보세요!',
    shortDescription: '나의 관종력 측정',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/attention-seeker.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58760,
    isPremium: false,
    price: 0,
    tags: ['관종', '관심', '재미', '자극적', '바이럴'],
    createdAt: '2024-11-26',
  },
  // Batch 6 - MBTI 확장 및 라이프스타일 테스트
  {
    id: 'mbti-shadow',
    title: 'MBTI 부캐 테스트',
    slug: 'mbti-shadow',
    description: '평소의 나와는 다른 또 다른 성격이 숨어있다면? 스트레스 상황에서 나타나는 그림자 MBTI, 숨겨진 부캐를 찾아보세요!',
    shortDescription: '숨겨진 또 다른 나의 MBTI',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/mbti-shadow.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 52340,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '부캐', '그림자', '성격', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'mbti-stress',
    title: 'MBTI 스트레스 반응 테스트',
    slug: 'mbti-stress',
    description: '스트레스 받으면 완전히 다른 사람이 된다고요? MBTI 유형별로 스트레스 상황에서 어떻게 변하는지 알아보세요!',
    shortDescription: '스트레스 받으면 나는 어떻게?',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/mbti-stress.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48760,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '스트레스', '성격변화', '심리', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'alpha-gen',
    title: '알파세대 이해력 테스트',
    slug: 'alpha-gen',
    description: '요즘 애들이 쓰는 말, 얼마나 알아들으세요? 알파세대 신조어, 문화, 트렌드 이해력을 측정합니다!',
    shortDescription: '요즘 애들 얼마나 알아?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/alpha-gen.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['알파세대', '트렌드', '신조어', 'MZ', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'digital-native',
    title: '디지털 네이티브 테스트',
    slug: 'digital-native',
    description: '당신은 디지털 원주민? 이주민? 디지털 기기와 인터넷 세상에 얼마나 적응했는지 측정합니다!',
    shortDescription: '디지털 세상 적응력 측정',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/digital-native.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 54320,
    isPremium: false,
    price: 0,
    tags: ['디지털', '테크', '적응력', 'MZ', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'midnight-snack',
    title: '야식 유형 테스트',
    slug: 'midnight-snack',
    description: '밤에 뭘 먹을지 고민되시나요? 당신의 야식 취향을 분석하고 딱 맞는 야식을 추천해드립니다!',
    shortDescription: '나에게 맞는 야식 찾기',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/midnight-snack.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 58940,
    isPremium: false,
    price: 0,
    tags: ['야식', '음식', '취향', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'travel-style',
    title: '여행 스타일 테스트',
    slug: 'travel-style',
    description: '빡빡한 일정파? 여유로운 힐링파? 당신의 여행 스타일을 분석하고 맞춤 여행지를 추천해드립니다!',
    shortDescription: '나의 여행 스타일 분석',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/travel-style.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 62340,
    isPremium: false,
    price: 0,
    tags: ['여행', '스타일', '취향', '라이프', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'shopping-type',
    title: '쇼핑 유형 테스트',
    slug: 'shopping-type',
    description: '계획적 쇼퍼? 충동 구매러? 당신의 쇼핑 패턴을 분석하고 현명한 소비 팁을 알려드립니다!',
    shortDescription: '나의 쇼핑 스타일 분석',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/shopping-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 51230,
    isPremium: false,
    price: 0,
    tags: ['쇼핑', '소비', '스타일', '라이프', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'pet-match',
    title: '반려동물 궁합 테스트',
    slug: 'pet-match',
    description: '나와 찰떡궁합인 반려동물은? 라이프스타일과 성격을 분석해서 딱 맞는 반려동물을 추천해드립니다!',
    shortDescription: '나에게 맞는 반려동물 찾기',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/pet-match.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 47890,
    isPremium: false,
    price: 0,
    tags: ['반려동물', '펫', '궁합', '라이프', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'zombie-survival',
    title: '좀비 서바이벌 테스트',
    slug: 'zombie-survival',
    description: '좀비 아포칼립스가 터졌다! 당신은 얼마나 오래 살아남을 수 있을까요? 생존 능력을 측정합니다!',
    shortDescription: '좀비 세상 생존력 측정',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/zombie-survival.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72450,
    isPremium: false,
    price: 0,
    tags: ['좀비', '서바이벌', '생존', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'island-survival',
    title: '무인도 서바이벌 테스트',
    slug: 'island-survival',
    description: '무인도에 떨어졌다면? 당신의 생존 전략과 능력을 분석하고 생존 기간을 예측합니다!',
    shortDescription: '무인도 생존력 측정',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/island-survival.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 68230,
    isPremium: false,
    price: 0,
    tags: ['무인도', '서바이벌', '생존', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'mbti-office',
    title: 'MBTI 직장 생존기 테스트',
    slug: 'mbti-office',
    description: '직장에서 나는 어떤 MBTI? 업무 스타일, 동료 관계, 스트레스 대처법까지 직장 속 나를 분석합니다.',
    shortDescription: '직장에서의 MBTI 유형',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/mbti-office.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72340,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '직장', '직장인', '커리어'],
    createdAt: '2024-11-26',
  },
  {
    id: 'mbti-dating',
    title: 'MBTI 연애할 때 테스트',
    slug: 'mbti-dating',
    description: '연애하면 달라지는 나! 연애할 때 나타나는 MBTI 특성과 사랑 표현 방식을 알아보세요.',
    shortDescription: '연애할 때 나의 MBTI',
    categoryId: 'relationship',
    thumbnailUrl: '/images/tests/mbti-dating.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 89560,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '연애', '사랑', '데이트'],
    createdAt: '2024-11-26',
  },
  {
    id: 'driving-personality',
    title: '운전 성격 테스트',
    slug: 'driving-personality',
    description: '핸들 잡으면 달라지는 나? 운전할 때 나타나는 성격 유형과 드라이빙 스타일을 분석합니다.',
    shortDescription: '운전할 때 나의 성격',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/driving-personality.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 54230,
    isPremium: false,
    price: 0,
    tags: ['운전', '드라이브', '성격', '재미'],
    createdAt: '2024-11-26',
  },
  {
    id: 'karaoke-type',
    title: '노래방 유형 테스트',
    slug: 'karaoke-type',
    description: '노래방 가면 나는 어떤 타입? 선곡 스타일부터 무대 매너까지, 당신의 노래방 유형을 알아보세요!',
    shortDescription: '노래방에서의 나는?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/karaoke-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 61450,
    isPremium: false,
    price: 0,
    tags: ['노래방', '노래', '재미', '친구'],
    createdAt: '2024-11-26',
  },
  {
    id: 'fashion-personality',
    title: '패션 성격 테스트',
    slug: 'fashion-personality',
    description: '옷으로 보는 나의 성격! 패션 스타일에 담긴 당신의 성격과 취향을 분석합니다.',
    shortDescription: '패션으로 보는 내 성격',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/fashion-personality.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 78920,
    isPremium: false,
    price: 0,
    tags: ['패션', '스타일', '옷', '성격'],
    createdAt: '2024-11-26',
  },
  {
    id: 'food-taste',
    title: '음식 취향 테스트',
    slug: 'food-taste',
    description: '먹는 것으로 보는 나의 성격! 음식 취향에 담긴 당신의 성격을 분석하고 맞춤 음식을 추천합니다.',
    shortDescription: '음식 취향으로 보는 성격',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/food-taste.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 82340,
    isPremium: false,
    price: 0,
    tags: ['음식', '맛집', '취향', '재미'],
    createdAt: '2024-11-26',
  },
  {
    id: 'room-cleaning',
    title: '방 정리 유형 테스트',
    slug: 'room-cleaning',
    description: '정리 스타일로 보는 나의 성격! 방 정리 습관에 담긴 당신의 성격 유형을 알아보세요.',
    shortDescription: '정리 습관으로 보는 성격',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/room-cleaning.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 56780,
    isPremium: false,
    price: 0,
    tags: ['정리', '청소', '방', '성격'],
    createdAt: '2024-11-26',
  },
  {
    id: 'hobby-recommend',
    title: '취미 추천 테스트',
    slug: 'hobby-recommend',
    description: '나에게 맞는 취미 찾기! 성격과 라이프스타일을 분석해 딱 맞는 취미를 추천합니다.',
    shortDescription: '나에게 맞는 취미 찾기',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/hobby-recommend.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 71230,
    isPremium: false,
    price: 0,
    tags: ['취미', '추천', '라이프스타일', '재미'],
    createdAt: '2024-11-26',
  },
  {
    id: 'morning-night',
    title: '아침형/저녁형 인간 테스트',
    slug: 'morning-night',
    description: '나는 얼리버드? 올빼미? 생체리듬 유형을 분석하고 최적의 라이프스타일을 찾아드립니다.',
    shortDescription: '나의 생체리듬 유형은?',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/morning-night.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 64890,
    isPremium: false,
    price: 0,
    tags: ['아침형', '저녁형', '생체리듬', '수면'],
    createdAt: '2024-11-26',
  },
  {
    id: 'season-personality',
    title: '계절 성격 테스트',
    slug: 'season-personality',
    description: '나를 닮은 계절은? 봄, 여름, 가을, 겨울 중 당신의 성격을 닮은 계절을 찾아드립니다.',
    shortDescription: '나를 닮은 계절 찾기',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/season-personality.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 73450,
    isPremium: false,
    price: 0,
    tags: ['계절', '성격', '봄여름가을겨울', '감성'],
    createdAt: '2024-11-26',
  },
  {
    id: 'mbti-travel',
    title: 'MBTI 여행 스타일 테스트',
    slug: 'mbti-travel',
    description: '여행할 때 나는 어떤 MBTI? 계획형 여행자부터 즉흥 모험가까지, 나의 여행 MBTI를 분석합니다.',
    shortDescription: '여행 스타일로 보는 MBTI',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/mbti-travel.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '여행', '스타일', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'mbti-drinking',
    title: 'MBTI 술자리 테스트',
    slug: 'mbti-drinking',
    description: '술자리에서 나는 어떤 MBTI? 파티킹부터 조용한 관찰자까지, 술자리에서의 나를 분석합니다.',
    shortDescription: '술자리에서의 MBTI 유형',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/mbti-drinking.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72340,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '술자리', '유머', '바이럴'],
    createdAt: '2024-11-26',
  },
  // Batch 8 - 판타지/재미 테스트
  {
    id: 'fairytale-role',
    title: '동화 속 역할 테스트',
    slug: 'fairytale-role',
    description: '동화 속에서 당신은 어떤 역할일까요? 용감한 영웅, 현명한 조력자, 신비로운 마법사, 아니면 숨겨진 악당? 당신의 동화 속 운명을 찾아보세요!',
    shortDescription: '동화 속 나의 역할은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/fairytale-role.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 54230,
    isPremium: false,
    price: 0,
    tags: ['동화', '판타지', '역할', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'magic-element',
    title: '마법 속성 테스트',
    slug: 'magic-element',
    description: '당신이 마법을 쓸 수 있다면 어떤 속성일까요? 불, 물, 바람, 땅, 빛, 어둠 중 당신의 영혼과 공명하는 마법 속성을 찾아보세요!',
    shortDescription: '나의 마법 속성은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/magic-element.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['마법', '속성', '판타지', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'game-character',
    title: '게임 캐릭터 테스트',
    slug: 'game-character',
    description: '게임 속에서 당신은 어떤 캐릭터일까요? 전사, 마법사, 힐러, 도적, 탱커 중 당신의 플레이 스타일과 성격에 맞는 직업을 찾아보세요!',
    shortDescription: '게임 속 나의 직업은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/game-character.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 72340,
    isPremium: false,
    price: 0,
    tags: ['게임', '캐릭터', '직업', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'super-power',
    title: '슈퍼파워 테스트',
    slug: 'super-power',
    description: '당신에게 초능력이 생긴다면? 텔레파시, 시간조작, 순간이동, 투명화 등 당신의 성격과 가치관에 맞는 슈퍼파워를 찾아보세요!',
    shortDescription: '나에게 맞는 초능력은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/super-power.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 81230,
    isPremium: false,
    price: 0,
    tags: ['초능력', '슈퍼파워', '판타지', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'hogwarts-house',
    title: '호그와트 기숙사 테스트',
    slug: 'hogwarts-house',
    description: '마법의 세계 호그와트에서 당신은 어느 기숙사에 배정될까요? 그리핀도르, 슬리데린, 래번클로, 후플푸프 중 당신의 운명을 결정하세요!',
    shortDescription: '나의 호그와트 기숙사는?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/hogwarts-house.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 89560,
    isPremium: false,
    price: 0,
    tags: ['해리포터', '호그와트', '판타지', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'meeting-type',
    title: '회의 유형 테스트',
    slug: 'meeting-type',
    description: '회의실에서 당신은 어떤 존재인가요? 아이디어 뱅크, 정리의 달인, 조용한 관찰자, 반박 전문가 중 당신의 회의 스타일을 알아보세요!',
    shortDescription: '회의에서 나는 어떤 유형?',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/meeting-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 48760,
    isPremium: false,
    price: 0,
    tags: ['회의', '직장', '커리어', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  // Batch 9 - MBTI 확장 및 트렌드/직장 테스트
  {
    id: 'mbti-conflict',
    title: 'MBTI 싸울 때 테스트',
    slug: 'mbti-conflict',
    description: '갈등 상황에서 당신의 MBTI는? 싸움 스타일, 화해 방식, 감정 표현 등 갈등 상황에서의 나를 분석합니다!',
    shortDescription: '싸울 때 나의 MBTI는?',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/mbti-conflict.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 67890,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '갈등', '성격', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'mbti-spending',
    title: 'MBTI 돈 쓸 때 테스트',
    slug: 'mbti-spending',
    description: '소비 패턴으로 보는 MBTI! 충동구매러? 계획 소비러? 돈 쓰는 방식으로 당신의 MBTI를 분석합니다!',
    shortDescription: '돈 쓸 때 나의 MBTI는?',
    categoryId: 'personality',
    thumbnailUrl: '/images/tests/mbti-spending.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 71230,
    isPremium: false,
    price: 0,
    tags: ['MBTI', '소비', '돈', '재테크', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'ajae-power',
    title: '아재력 테스트',
    slug: 'ajae-power',
    description: '당신의 아재/아줌마력은 몇 점? 아재개그 센스부터 옛날 감성까지, 당신 안에 숨어있는 아재력을 측정합니다!',
    shortDescription: '나의 아재력 레벨은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/ajae-power.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 82340,
    isPremium: false,
    price: 0,
    tags: ['아재', '유머', '세대', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'hipster-level',
    title: '힙스터 레벨 테스트',
    slug: 'hipster-level',
    description: '당신은 얼마나 힙한가요? 메인스트림을 거부하고 독특한 취향을 추구하는 당신의 힙스터 지수를 측정합니다!',
    shortDescription: '나의 힙스터 레벨은?',
    categoryId: 'fun',
    thumbnailUrl: '/images/tests/hipster-level.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 59870,
    isPremium: false,
    price: 0,
    tags: ['힙스터', '트렌드', '취향', '재미', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'monday-blues',
    title: '월요병 지수 테스트',
    slug: 'monday-blues',
    description: '당신의 월요병은 몇 단계? 일요일 저녁부터 시작되는 우울함의 정도를 측정하고 극복 방법을 알려드립니다!',
    shortDescription: '나의 월요병 레벨은?',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/monday-blues.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 91230,
    isPremium: false,
    price: 0,
    tags: ['월요병', '직장', '스트레스', '바이럴'],
    createdAt: '2024-11-26',
  },
  {
    id: 'boss-type',
    title: '상사 유형 테스트',
    slug: 'boss-type',
    description: '당신은 어떤 유형의 상사/리더일까요? 멘토형, 친구형, 완벽주의형, 비전형, 카리스마형 중 나의 리더십을 분석합니다!',
    shortDescription: '나는 어떤 유형의 상사?',
    categoryId: 'career',
    thumbnailUrl: '/images/tests/boss-type.png',
    questionCount: 12,
    estimatedTime: 3,
    participantCount: 53680,
    isPremium: false,
    price: 0,
    tags: ['상사', '리더십', '직장', '커리어', '바이럴'],
    createdAt: '2024-11-26',
  },
];

// 유틸리티 함수들
export function getTestsByCategory(categoryId: string): Test[] {
  return tests.filter((test) => test.categoryId === categoryId);
}

export function getTestBySlug(slug: string): Test | undefined {
  return tests.find((test) => test.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((category) => category.slug === slug);
}

export function getPopularTests(limit: number = 6): Test[] {
  return [...tests].sort((a, b) => b.participantCount - a.participantCount).slice(0, limit);
}

export function getFreeTests(): Test[] {
  return tests.filter((test) => !test.isPremium);
}

export function getPremiumTests(): Test[] {
  return tests.filter((test) => test.isPremium);
}

export function formatParticipantCount(count: number): string {
  if (count >= 10000) {
    return `${(count / 10000).toFixed(1)}만명`;
  }
  if (count >= 1000) {
    return `${(count / 1000).toFixed(1)}천명`;
  }
  return `${count}명`;
}
