// Hindi Test Data (हिंदी टेस्ट डेटा)
// 힌디어 테스트 메타데이터
// Auto-generated: 2024-12-05
// Total: 315 tests (50 personality + 60 psychology + 50 relationship + 45 career + 95 fun + 15 iq)

export interface TestHi {
  id: string;
  title: string;
  slug: string;
  description: string;
  shortDescription: string;
  categoryId: string;
  thumbnailUrl?: string;
  questionCount: number;
  estimatedTime: number;
  participantCount: number;
  tags: string[];
  createdAt: string;
}

export interface CategoryHi {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
}

export const categoriesHi: CategoryHi[] = [
  {
    id: 'personality',
    name: 'व्यक्तित्व',
    slug: 'personality',
    description: 'अपने व्यक्तित्व को जानें',
    icon: 'Brain',
    color: 'purple',
  },
  {
    id: 'psychology',
    name: 'मनोविज्ञान',
    slug: 'psychology',
    description: 'अपने मन को गहराई से समझें',
    icon: 'Heart',
    color: 'blue',
  },
  {
    id: 'relationship',
    name: 'रिश्ते',
    slug: 'relationship',
    description: 'प्यार और रिश्तों के बारे में टेस्ट',
    icon: 'Users',
    color: 'pink',
  },
  {
    id: 'career',
    name: 'करियर',
    slug: 'career',
    description: 'अपनी करियर क्षमता को जानें',
    icon: 'Briefcase',
    color: 'green',
  },
  {
    id: 'fun',
    name: 'मज़ेदार',
    slug: 'fun',
    description: 'मज़ेदार और रोचक टेस्ट',
    icon: 'Sparkles',
    color: 'yellow',
  },
  {
    id: 'iq',
    name: 'IQ/बुद्धि',
    slug: 'iq',
    description: 'अपनी बुद्धिमत्ता जाँचें',
    icon: 'Lightbulb',
    color: 'orange',
  },
];

// Psychology Tests (मनोविज्ञान टेस्ट) - mano- prefix - 60 tests
const manoTests = [
  'mano-aaram', 'mano-aasha', 'mano-aatmvishwas', 'mano-abhilasha', 'mano-akela',
  'mano-asafalta', 'mano-atmsamman', 'mano-badlav', 'mano-bhavna', 'mano-chinta',
  'mano-dar', 'mano-daya', 'mano-dhairya', 'mano-dosti', 'mano-hal',
  'mano-himmat', 'mano-irrsha', 'mano-kaam', 'mano-khushi', 'mano-krodh',
  'mano-laalach', 'mano-lagav', 'mano-lakshya', 'mano-masti', 'mano-neend',
  'mano-netritva', 'mano-nirasha', 'mano-nirnay', 'mano-paisa', 'mano-parivar',
  'mano-pratibha', 'mano-prayas', 'mano-prem', 'mano-prerana', 'mano-rachnatmak',
  'mano-safalta', 'mano-sahaj', 'mano-sahayog', 'mano-samajh', 'mano-samasya',
  'mano-samay', 'mano-sambandh', 'mano-samvad', 'mano-samvedna', 'mano-sankalp',
  'mano-santulan', 'mano-santushti', 'mano-shanti', 'mano-shraddha', 'mano-soch',
  'mano-sudhar', 'mano-swabhiman', 'mano-swikaar', 'mano-tanaav', 'mano-tanav-mukti',
  'mano-tyag', 'mano-utsah', 'mano-vichar', 'mano-vishwas', 'mano-vyavastha'
];

// Relationship Tests (रिश्ते टेस्ट) - rishta- prefix - 50 tests
const rishtaTests = [
  'rishta-anniversary', 'rishta-arranged', 'rishta-attachment', 'rishta-boundaries', 'rishta-breakup',
  'rishta-career-balance', 'rishta-children', 'rishta-commitment', 'rishta-communication', 'rishta-compatibility',
  'rishta-conflict', 'rishta-dating-style', 'rishta-dosti', 'rishta-expectations', 'rishta-finances',
  'rishta-first-love', 'rishta-forgiveness', 'rishta-freedom', 'rishta-future', 'rishta-gifts',
  'rishta-growth', 'rishta-honeymoon', 'rishta-inlaws', 'rishta-intimacy', 'rishta-jealousy',
  'rishta-jhagda', 'rishta-joint-family', 'rishta-long-distance', 'rishta-love-marriage', 'rishta-loyalty',
  'rishta-milan', 'rishta-nuclear-family', 'rishta-online-dating', 'rishta-parivar', 'rishta-priorities',
  'rishta-proposal', 'rishta-pyar', 'rishta-quality-time', 'rishta-respect', 'rishta-romance',
  'rishta-saathi', 'rishta-samjhauta', 'rishta-sasural', 'rishta-service', 'rishta-shaadi',
  'rishta-support', 'rishta-touch', 'rishta-values', 'rishta-vishwas', 'rishta-words'
];

// Personality Tests (व्यक्तित्व टेस्ट) - vyaktitva- prefix - 50 tests
const vyaktitvaTests = [
  'vyaktitva-argument', 'vyaktitva-bollywood', 'vyaktitva-boss', 'vyaktitva-chai', 'vyaktitva-creativity',
  'vyaktitva-cricket', 'vyaktitva-dating', 'vyaktitva-decision', 'vyaktitva-diwali', 'vyaktitva-dosti',
  'vyaktitva-emotional-intelligence', 'vyaktitva-festival', 'vyaktitva-fitness', 'vyaktitva-friendship-test', 'vyaktitva-gussa',
  'vyaktitva-holi', 'vyaktitva-introvert-extrovert', 'vyaktitva-kaam', 'vyaktitva-khana', 'vyaktitva-kitchen',
  'vyaktitva-leadership', 'vyaktitva-monsoon', 'vyaktitva-music', 'vyaktitva-neighbor', 'vyaktitva-office-politics',
  'vyaktitva-padhai', 'vyaktitva-paisa', 'vyaktitva-parenting', 'vyaktitva-parivar', 'vyaktitva-patience',
  'vyaktitva-phone', 'vyaktitva-pyaar', 'vyaktitva-retirement', 'vyaktitva-risk', 'vyaktitva-sanskar',
  'vyaktitva-sapne', 'vyaktitva-shaadi', 'vyaktitva-shopping', 'vyaktitva-sleep', 'vyaktitva-social-gatherings',
  'vyaktitva-social-media', 'vyaktitva-spirituality', 'vyaktitva-stress', 'vyaktitva-subah', 'vyaktitva-swabhav',
  'vyaktitva-technology', 'vyaktitva-time-management', 'vyaktitva-traffic', 'vyaktitva-travel', 'vyaktitva-wedding-guest'
];

// Career Tests (करियर टेस्ट) - kareer- prefix - 45 tests
const kareerTests = [
  'kareer-abroad', 'kareer-boss', 'kareer-burnout', 'kareer-colleague', 'kareer-communication',
  'kareer-conflict', 'kareer-consulting', 'kareer-creative', 'kareer-deadline', 'kareer-engineering',
  'kareer-family-business', 'kareer-finance', 'kareer-freelance', 'kareer-goal', 'kareer-government',
  'kareer-hr', 'kareer-interview', 'kareer-it', 'kareer-law', 'kareer-marketing',
  'kareer-mba', 'kareer-medical', 'kareer-mentor', 'kareer-motivation', 'kareer-multitask',
  'kareer-naukri', 'kareer-netritva', 'kareer-networking', 'kareer-office', 'kareer-presentation',
  'kareer-promotion', 'kareer-research', 'kareer-salary', 'kareer-sales', 'kareer-samay',
  'kareer-skills', 'kareer-startup', 'kareer-switch', 'kareer-tanaav', 'kareer-teaching',
  'kareer-teamwork', 'kareer-vyapar', 'kareer-wfh', 'kareer-work-life', 'kareer-yogyata'
];

// Fun Tests (मज़ेदार टेस्ट) - mazaa- prefix - 95 tests
const mazaaTests = [
  'mazaa-airport', 'mazaa-aunty', 'mazaa-baarish', 'mazaa-barber', 'mazaa-bargain',
  'mazaa-beach', 'mazaa-bike', 'mazaa-biryani', 'mazaa-bollywood', 'mazaa-book',
  'mazaa-boss', 'mazaa-bus', 'mazaa-car', 'mazaa-chai', 'mazaa-child',
  'mazaa-chutney', 'mazaa-circus', 'mazaa-city', 'mazaa-colleague', 'mazaa-courier',
  'mazaa-cricket', 'mazaa-cycle', 'mazaa-dal', 'mazaa-dance', 'mazaa-desert',
  'mazaa-diwali', 'mazaa-doctor', 'mazaa-dosa', 'mazaa-dream', 'mazaa-food',
  'mazaa-garmi', 'mazaa-gully', 'mazaa-gym', 'mazaa-heroine', 'mazaa-hill',
  'mazaa-holi', 'mazaa-insta', 'mazaa-ipl', 'mazaa-jog', 'mazaa-jungle',
  'mazaa-laptop', 'mazaa-lassi', 'mazaa-mela', 'mazaa-metro', 'mazaa-mithai',
  'mazaa-mohalla', 'mazaa-movie-genre', 'mazaa-museum', 'mazaa-music', 'mazaa-nap',
  'mazaa-neighbor', 'mazaa-newspaper', 'mazaa-paan', 'mazaa-paneer', 'mazaa-paratha',
  'mazaa-parent', 'mazaa-park', 'mazaa-parking', 'mazaa-pet', 'mazaa-phone',
  'mazaa-pickle', 'mazaa-radio', 'mazaa-raita', 'mazaa-relative', 'mazaa-rickshaw',
  'mazaa-river', 'mazaa-roti', 'mazaa-sabzi', 'mazaa-samosa', 'mazaa-sardi',
  'mazaa-scooter', 'mazaa-shaadi', 'mazaa-shopkeeper', 'mazaa-shopping', 'mazaa-sleep',
  'mazaa-state', 'mazaa-street-food', 'mazaa-student', 'mazaa-supari', 'mazaa-tailor',
  'mazaa-tandoor', 'mazaa-temple', 'mazaa-thali', 'mazaa-tinder', 'mazaa-traffic',
  'mazaa-train', 'mazaa-tutor', 'mazaa-tv', 'mazaa-uncle', 'mazaa-villain',
  'mazaa-walk', 'mazaa-watchman', 'mazaa-whatsapp', 'mazaa-yoga', 'mazaa-zoo'
];

// IQ Tests (बुद्धि टेस्ट) - buddhi- prefix - 15 tests
const buddhiTests = [
  'buddhi-creative', 'buddhi-dhyan', 'buddhi-emotional', 'buddhi-ganit', 'buddhi-observation',
  'buddhi-pattern', 'buddhi-problem-solving', 'buddhi-reasoning', 'buddhi-samanya-gyan', 'buddhi-shabdawali',
  'buddhi-smriti', 'buddhi-spatial', 'buddhi-speed', 'buddhi-tark', 'buddhi-vishleshan'
];

// Hindi titles mapping for better display
const hindiTitles: Record<string, string> = {
  // Mano (Psychology) tests - 60
  'mano-aaram': 'आराम शैली',
  'mano-aasha': 'आशावाद स्तर',
  'mano-aatmvishwas': 'आत्मविश्वास',
  'mano-abhilasha': 'अभिलाषा शैली',
  'mano-akela': 'अकेलापन',
  'mano-asafalta': 'असफलता से निपटना',
  'mano-atmsamman': 'आत्मसम्मान',
  'mano-badlav': 'बदलाव स्वीकृति',
  'mano-bhavna': 'भावना नियंत्रण',
  'mano-chinta': 'चिंता स्तर',
  'mano-dar': 'डर से निपटना',
  'mano-daya': 'दया भाव',
  'mano-dhairya': 'धैर्य स्तर',
  'mano-dosti': 'दोस्ती शैली',
  'mano-hal': 'समस्या हल',
  'mano-himmat': 'हिम्मत स्तर',
  'mano-irrsha': 'ईर्ष्या स्तर',
  'mano-kaam': 'काम शैली',
  'mano-khushi': 'खुशी स्तर',
  'mano-krodh': 'क्रोध प्रबंधन',
  'mano-laalach': 'लालच नियंत्रण',
  'mano-lagav': 'लगाव शैली',
  'mano-lakshya': 'लक्ष्य निर्धारण',
  'mano-masti': 'मस्ती स्तर',
  'mano-neend': 'नींद शैली',
  'mano-netritva': 'नेतृत्व क्षमता',
  'mano-nirasha': 'निराशा से निपटना',
  'mano-nirnay': 'निर्णय क्षमता',
  'mano-paisa': 'पैसा मानसिकता',
  'mano-parivar': 'परिवार बंधन',
  'mano-pratibha': 'प्रतिभा पहचान',
  'mano-prayas': 'प्रयास स्तर',
  'mano-prem': 'प्रेम भाषा',
  'mano-prerana': 'प्रेरणा स्रोत',
  'mano-rachnatmak': 'रचनात्मकता',
  'mano-safalta': 'सफलता मानसिकता',
  'mano-sahaj': 'सहजता स्तर',
  'mano-sahayog': 'सहयोग शैली',
  'mano-samajh': 'समझ शक्ति',
  'mano-samasya': 'समस्या समाधान',
  'mano-samay': 'समय प्रबंधन',
  'mano-sambandh': 'संबंध शैली',
  'mano-samvad': 'संवाद कौशल',
  'mano-samvedna': 'संवेदना स्तर',
  'mano-sankalp': 'संकल्प शक्ति',
  'mano-santulan': 'संतुलन क्षमता',
  'mano-santushti': 'संतुष्टि स्तर',
  'mano-shanti': 'शांति स्तर',
  'mano-shraddha': 'श्रद्धा भाव',
  'mano-soch': 'सोच शैली',
  'mano-sudhar': 'आत्म सुधार',
  'mano-swabhiman': 'स्वाभिमान',
  'mano-swikaar': 'स्वीकार क्षमता',
  'mano-tanaav': 'तनाव स्तर',
  'mano-tanav-mukti': 'तनाव मुक्ति',
  'mano-tyag': 'त्याग भाव',
  'mano-utsah': 'उत्साह स्तर',
  'mano-vichar': 'विचार शैली',
  'mano-vishwas': 'विश्वास स्तर',
  'mano-vyavastha': 'व्यवस्था कौशल',
  
  // Rishta (Relationship) tests - 50
  'rishta-anniversary': 'सालगिरह शैली',
  'rishta-arranged': 'अरेंज्ड मैरिज',
  'rishta-attachment': 'लगाव शैली',
  'rishta-boundaries': 'सीमाएं',
  'rishta-breakup': 'ब्रेकअप से निपटना',
  'rishta-career-balance': 'करियर संतुलन',
  'rishta-children': 'बच्चों का पालन',
  'rishta-commitment': 'प्रतिबद्धता',
  'rishta-communication': 'संवाद शैली',
  'rishta-compatibility': 'अनुकूलता',
  'rishta-conflict': 'टकराव समाधान',
  'rishta-dating-style': 'डेटिंग शैली',
  'rishta-dosti': 'दोस्ती का प्रकार',
  'rishta-expectations': 'अपेक्षाएं',
  'rishta-finances': 'आर्थिक मामले',
  'rishta-first-love': 'पहला प्यार',
  'rishta-forgiveness': 'माफी शैली',
  'rishta-freedom': 'आज़ादी',
  'rishta-future': 'भविष्य योजना',
  'rishta-gifts': 'उपहार शैली',
  'rishta-growth': 'विकास शैली',
  'rishta-honeymoon': 'हनीमून शैली',
  'rishta-inlaws': 'ससुराल संबंध',
  'rishta-intimacy': 'नज़दीकी',
  'rishta-jealousy': 'जलन स्तर',
  'rishta-jhagda': 'झगड़े का तरीका',
  'rishta-joint-family': 'संयुक्त परिवार',
  'rishta-long-distance': 'लॉन्ग डिस्टेंस',
  'rishta-love-marriage': 'लव मैरिज',
  'rishta-loyalty': 'वफादारी शैली',
  'rishta-milan': 'जोड़ी मिलान',
  'rishta-nuclear-family': 'न्यूक्लियर फैमिली',
  'rishta-online-dating': 'ऑनलाइन डेटिंग',
  'rishta-parivar': 'परिवार के रिश्ते',
  'rishta-priorities': 'प्राथमिकताएं',
  'rishta-proposal': 'प्रपोज़ल शैली',
  'rishta-pyar': 'प्यार की भाषा',
  'rishta-quality-time': 'क्वालिटी टाइम',
  'rishta-respect': 'सम्मान',
  'rishta-romance': 'रोमांस शैली',
  'rishta-saathi': 'आदर्श साथी',
  'rishta-samjhauta': 'समझौता शैली',
  'rishta-sasural': 'ससुराल संबंध',
  'rishta-service': 'सेवा भाव',
  'rishta-shaadi': 'शादी की तैयारी',
  'rishta-support': 'सहारा देना',
  'rishta-touch': 'स्पर्श भाषा',
  'rishta-values': 'मूल्य',
  'rishta-vishwas': 'विश्वास का स्तर',
  'rishta-words': 'शब्दों की भाषा',
  
  // Vyaktitva (Personality) tests - 50
  'vyaktitva-argument': 'बहस शैली',
  'vyaktitva-bollywood': 'बॉलीवुड व्यक्तित्व',
  'vyaktitva-boss': 'बॉस के साथ',
  'vyaktitva-chai': 'चाय व्यक्तित्व',
  'vyaktitva-creativity': 'रचनात्मकता',
  'vyaktitva-cricket': 'क्रिकेट शैली',
  'vyaktitva-dating': 'डेटिंग व्यक्तित्व',
  'vyaktitva-decision': 'निर्णय शैली',
  'vyaktitva-diwali': 'दिवाली शैली',
  'vyaktitva-dosti': 'दोस्ती व्यक्तित्व',
  'vyaktitva-emotional-intelligence': 'भावनात्मक बुद्धि',
  'vyaktitva-festival': 'त्योहार शैली',
  'vyaktitva-fitness': 'फिटनेस व्यक्तित्व',
  'vyaktitva-friendship-test': 'दोस्ती टेस्ट',
  'vyaktitva-gussa': 'गुस्सा शैली',
  'vyaktitva-holi': 'होली शैली',
  'vyaktitva-introvert-extrovert': 'अंतर्मुखी/बहिर्मुखी',
  'vyaktitva-kaam': 'काम व्यक्तित्व',
  'vyaktitva-khana': 'खाना व्यक्तित्व',
  'vyaktitva-kitchen': 'किचन शैली',
  'vyaktitva-leadership': 'नेतृत्व शैली',
  'vyaktitva-monsoon': 'मानसून व्यक्तित्व',
  'vyaktitva-music': 'म्यूज़िक व्यक्तित्व',
  'vyaktitva-neighbor': 'पड़ोसी शैली',
  'vyaktitva-office-politics': 'ऑफिस पॉलिटिक्स',
  'vyaktitva-padhai': 'पढ़ाई शैली',
  'vyaktitva-paisa': 'पैसा व्यक्तित्व',
  'vyaktitva-parenting': 'पेरेंटिंग शैली',
  'vyaktitva-parivar': 'परिवार व्यक्तित्व',
  'vyaktitva-patience': 'धैर्य शैली',
  'vyaktitva-phone': 'फोन व्यक्तित्व',
  'vyaktitva-pyaar': 'प्यार व्यक्तित्व',
  'vyaktitva-retirement': 'रिटायरमेंट शैली',
  'vyaktitva-risk': 'रिस्क लेने की शैली',
  'vyaktitva-sanskar': 'संस्कार व्यक्तित्व',
  'vyaktitva-sapne': 'सपने व्यक्तित्व',
  'vyaktitva-shaadi': 'शादी व्यक्तित्व',
  'vyaktitva-shopping': 'शॉपिंग व्यक्तित्व',
  'vyaktitva-sleep': 'नींद व्यक्तित्व',
  'vyaktitva-social-gatherings': 'सोशल गैदरिंग',
  'vyaktitva-social-media': 'सोशल मीडिया',
  'vyaktitva-spirituality': 'आध्यात्मिकता',
  'vyaktitva-stress': 'तनाव व्यक्तित्व',
  'vyaktitva-subah': 'सुबह व्यक्तित्व',
  'vyaktitva-swabhav': 'स्वभाव',
  'vyaktitva-technology': 'टेक्नोलॉजी शैली',
  'vyaktitva-time-management': 'समय प्रबंधन',
  'vyaktitva-traffic': 'ट्रैफिक व्यक्तित्व',
  'vyaktitva-travel': 'ट्रैवल व्यक्तित्व',
  'vyaktitva-wedding-guest': 'शादी का मेहमान',

  // Kareer (Career) tests - 45
  'kareer-abroad': 'विदेश में करियर',
  'kareer-boss': 'बॉस संबंध',
  'kareer-burnout': 'बर्नआउट स्तर',
  'kareer-colleague': 'सहकर्मी संबंध',
  'kareer-communication': 'संवाद कौशल',
  'kareer-conflict': 'टकराव प्रबंधन',
  'kareer-consulting': 'कंसल्टिंग योग्यता',
  'kareer-creative': 'क्रिएटिव करियर',
  'kareer-deadline': 'डेडलाइन प्रबंधन',
  'kareer-engineering': 'इंजीनियरिंग योग्यता',
  'kareer-family-business': 'पारिवारिक व्यापार',
  'kareer-finance': 'फाइनेंस योग्यता',
  'kareer-freelance': 'फ्रीलांस योग्यता',
  'kareer-goal': 'करियर लक्ष्य',
  'kareer-government': 'सरकारी नौकरी',
  'kareer-hr': 'एचआर योग्यता',
  'kareer-interview': 'इंटरव्यू स्टाइल',
  'kareer-it': 'आईटी योग्यता',
  'kareer-law': 'कानून योग्यता',
  'kareer-marketing': 'मार्केटिंग योग्यता',
  'kareer-mba': 'एमबीए योग्यता',
  'kareer-medical': 'मेडिकल योग्यता',
  'kareer-mentor': 'मेंटर शैली',
  'kareer-motivation': 'प्रेरणा स्तर',
  'kareer-multitask': 'मल्टीटास्किंग',
  'kareer-naukri': 'नौकरी योग्यता',
  'kareer-netritva': 'नेतृत्व क्षमता',
  'kareer-networking': 'नेटवर्किंग',
  'kareer-office': 'ऑफिस व्यक्तित्व',
  'kareer-presentation': 'प्रेजेंटेशन कौशल',
  'kareer-promotion': 'प्रमोशन तैयारी',
  'kareer-research': 'रिसर्च योग्यता',
  'kareer-salary': 'सैलरी बातचीत',
  'kareer-sales': 'सेल्स योग्यता',
  'kareer-samay': 'समय प्रबंधन',
  'kareer-skills': 'कौशल विकास',
  'kareer-startup': 'स्टार्टअप योग्यता',
  'kareer-switch': 'करियर स्विच',
  'kareer-tanaav': 'कार्य तनाव',
  'kareer-teaching': 'टीचिंग योग्यता',
  'kareer-teamwork': 'टीमवर्क',
  'kareer-vyapar': 'व्यापार योग्यता',
  'kareer-wfh': 'वर्क फ्रॉम होम',
  'kareer-work-life': 'वर्क-लाइफ बैलेंस',
  'kareer-yogyata': 'करियर योग्यता',

  // Mazaa (Fun) tests - 95
  'mazaa-airport': 'एयरपोर्ट व्यक्तित्व',
  'mazaa-aunty': 'आंटी टाइप',
  'mazaa-baarish': 'बारिश व्यक्तित्व',
  'mazaa-barber': 'नाई की दुकान',
  'mazaa-bargain': 'मोल-भाव शैली',
  'mazaa-beach': 'बीच व्यक्तित्व',
  'mazaa-bike': 'बाइक व्यक्तित्व',
  'mazaa-biryani': 'बिरयानी टाइप',
  'mazaa-bollywood': 'बॉलीवुड हीरो',
  'mazaa-book': 'किताब व्यक्तित्व',
  'mazaa-boss': 'बॉस टाइप',
  'mazaa-bus': 'बस यात्री',
  'mazaa-car': 'कार व्यक्तित्व',
  'mazaa-chai': 'चाय टाइप',
  'mazaa-child': 'बच्चा टाइप',
  'mazaa-chutney': 'चटनी टाइप',
  'mazaa-circus': 'सर्कस व्यक्तित्व',
  'mazaa-city': 'शहर व्यक्तित्व',
  'mazaa-colleague': 'सहकर्मी टाइप',
  'mazaa-courier': 'कूरियर व्यक्तित्व',
  'mazaa-cricket': 'क्रिकेट खिलाड़ी',
  'mazaa-cycle': 'साइकिल व्यक्तित्व',
  'mazaa-dal': 'दाल टाइप',
  'mazaa-dance': 'डांस स्टाइल',
  'mazaa-desert': 'रेगिस्तान व्यक्तित्व',
  'mazaa-diwali': 'दिवाली टाइप',
  'mazaa-doctor': 'डॉक्टर टाइप',
  'mazaa-dosa': 'डोसा टाइप',
  'mazaa-dream': 'सपना व्यक्तित्व',
  'mazaa-food': 'खाना व्यक्तित्व',
  'mazaa-garmi': 'गर्मी व्यक्तित्व',
  'mazaa-gully': 'गली व्यक्तित्व',
  'mazaa-gym': 'जिम व्यक्तित्व',
  'mazaa-heroine': 'बॉलीवुड हीरोइन',
  'mazaa-hill': 'पहाड़ व्यक्तित्व',
  'mazaa-holi': 'होली टाइप',
  'mazaa-insta': 'इंस्टाग्राम व्यक्तित्व',
  'mazaa-ipl': 'आईपीएल टीम',
  'mazaa-jog': 'जॉगिंग व्यक्तित्व',
  'mazaa-jungle': 'जंगल व्यक्तित्व',
  'mazaa-laptop': 'लैपटॉप व्यक्तित्व',
  'mazaa-lassi': 'लस्सी टाइप',
  'mazaa-mela': 'मेला व्यक्तित्व',
  'mazaa-metro': 'मेट्रो यात्री',
  'mazaa-mithai': 'मिठाई टाइप',
  'mazaa-mohalla': 'मोहल्ला व्यक्तित्व',
  'mazaa-movie-genre': 'फिल्म जॉनर',
  'mazaa-museum': 'म्यूज़ियम व्यक्तित्व',
  'mazaa-music': 'म्यूज़िक टाइप',
  'mazaa-nap': 'झपकी व्यक्तित्व',
  'mazaa-neighbor': 'पड़ोसी टाइप',
  'mazaa-newspaper': 'अखबार व्यक्तित्व',
  'mazaa-paan': 'पान टाइप',
  'mazaa-paneer': 'पनीर टाइप',
  'mazaa-paratha': 'पराठा टाइप',
  'mazaa-parent': 'पैरेंट टाइप',
  'mazaa-park': 'पार्क व्यक्तित्व',
  'mazaa-parking': 'पार्किंग व्यक्तित्व',
  'mazaa-pet': 'पालतू जानवर',
  'mazaa-phone': 'फोन व्यक्तित्व',
  'mazaa-pickle': 'अचार टाइप',
  'mazaa-radio': 'रेडियो व्यक्तित्व',
  'mazaa-raita': 'रायता टाइप',
  'mazaa-relative': 'रिश्तेदार टाइप',
  'mazaa-rickshaw': 'रिक्शा व्यक्तित्व',
  'mazaa-river': 'नदी व्यक्तित्व',
  'mazaa-roti': 'रोटी टाइप',
  'mazaa-sabzi': 'सब्ज़ी टाइप',
  'mazaa-samosa': 'समोसा टाइप',
  'mazaa-sardi': 'सर्दी व्यक्तित्व',
  'mazaa-scooter': 'स्कूटर व्यक्तित्व',
  'mazaa-shaadi': 'शादी मेहमान',
  'mazaa-shopkeeper': 'दुकानदार टाइप',
  'mazaa-shopping': 'शॉपिंग व्यक्तित्व',
  'mazaa-sleep': 'नींद व्यक्तित्व',
  'mazaa-state': 'राज्य व्यक्तित्व',
  'mazaa-street-food': 'स्ट्रीट फूड',
  'mazaa-student': 'स्टूडेंट टाइप',
  'mazaa-supari': 'सुपारी व्यक्तित्व',
  'mazaa-tailor': 'दर्ज़ी व्यक्तित्व',
  'mazaa-tandoor': 'तंदूर व्यक्तित्व',
  'mazaa-temple': 'मंदिर व्यक्तित्व',
  'mazaa-thali': 'थाली टाइप',
  'mazaa-tinder': 'टिंडर व्यक्तित्व',
  'mazaa-traffic': 'ट्रैफिक व्यक्तित्व',
  'mazaa-train': 'ट्रेन यात्री',
  'mazaa-tutor': 'ट्यूटर टाइप',
  'mazaa-tv': 'टीवी व्यक्तित्व',
  'mazaa-uncle': 'अंकल टाइप',
  'mazaa-villain': 'विलन टाइप',
  'mazaa-walk': 'वॉक व्यक्तित्व',
  'mazaa-watchman': 'वॉचमैन व्यक्तित्व',
  'mazaa-whatsapp': 'व्हाट्सएप व्यक्तित्व',
  'mazaa-yoga': 'योगा टाइप',
  'mazaa-zoo': 'चिड़ियाघर व्यक्तित्व',

  // Buddhi (IQ) tests - 15
  'buddhi-creative': 'रचनात्मक बुद्धि',
  'buddhi-dhyan': 'एकाग्रता टेस्ट',
  'buddhi-emotional': 'भावनात्मक बुद्धि',
  'buddhi-ganit': 'गणित क्षमता',
  'buddhi-observation': 'अवलोकन क्षमता',
  'buddhi-pattern': 'पैटर्न पहचान',
  'buddhi-problem-solving': 'समस्या समाधान',
  'buddhi-reasoning': 'तर्क क्षमता',
  'buddhi-samanya-gyan': 'सामान्य ज्ञान',
  'buddhi-shabdawali': 'शब्दावली टेस्ट',
  'buddhi-smriti': 'याददाश्त टेस्ट',
  'buddhi-spatial': 'स्थानिक बुद्धि',
  'buddhi-speed': 'मानसिक गति',
  'buddhi-tark': 'तार्किक बुद्धि',
  'buddhi-vishleshan': 'विश्लेषण क्षमता',
};

// Helper function to generate title from slug
function formatTitle(slug: string): string {
  return slug
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Category descriptions for different test types
const categoryDescriptions: Record<string, string> = {
  psychology: 'अपने मन को गहराई से समझें',
  relationship: 'अपने रिश्तों को बेहतर समझें',
  personality: 'अपने व्यक्तित्व को जानें',
  career: 'अपनी करियर क्षमता को जानें',
  fun: 'मज़ेदार और रोचक टेस्ट',
  iq: 'अपनी बुद्धिमत्ता जाँचें',
};


// Content-specific tags in Hindi based on test slug
const testTagsHi: Record<string, string[]> = {
  // === VYAKTITVA (성격) ===
  'vyaktitva-argument': ['व्यक्तित्व', 'बहस', 'संवाद'],
  'vyaktitva-bollywood': ['व्यक्तित्व', 'बॉलीवुड', 'मनोरंजन'],
  'vyaktitva-boss': ['व्यक्तित्व', 'काम', 'बॉस'],
  'vyaktitva-chai': ['व्यक्तित्व', 'चाय', 'वायरल'],
  'vyaktitva-creativity': ['व्यक्तित्व', 'रचनात्मक', 'सोच'],
  'vyaktitva-cricket': ['व्यक्तित्व', 'क्रिकेट', 'खेल'],
  'vyaktitva-dating': ['व्यक्तित्व', 'डेटिंग', 'प्यार'],
  'vyaktitva-decision': ['व्यक्तित्व', 'निर्णय', 'दिमाग'],
  'vyaktitva-diwali': ['व्यक्तित्व', 'दिवाली', 'त्योहार'],
  'vyaktitva-dosti': ['व्यक्तित्व', 'दोस्ती', 'रिश्ता'],
  'vyaktitva-emotional-intelligence': ['व्यक्तित्व', 'EQ', 'भावना'],
  'vyaktitva-festival': ['व्यक्तित्व', 'त्योहार', 'भारत'],
  'vyaktitva-fitness': ['व्यक्तित्व', 'फिटनेस', 'स्वास्थ्य'],
  'vyaktitva-friendship-test': ['व्यक्तित्व', 'दोस्ती', 'रिश्ता'],
  'vyaktitva-gussa': ['व्यक्तित्व', 'गुस्सा', 'भावना'],
  'vyaktitva-holi': ['व्यक्तित्व', 'होली', 'त्योहार'],
  'vyaktitva-introvert-extrovert': ['व्यक्तित्व', 'वायरल', 'सामाजिक'],
  'vyaktitva-kaam': ['व्यक्तित्व', 'काम', 'करियर'],
  'vyaktitva-khana': ['व्यक्तित्व', 'खाना', 'पसंद'],
  'vyaktitva-kitchen': ['व्यक्तित्व', 'खाना', 'घर'],
  'vyaktitva-leadership': ['व्यक्तित्व', 'नेतृत्व', 'करियर'],
  'vyaktitva-monsoon': ['व्यक्तित्व', 'बारिश', 'मौसम'],
  'vyaktitva-music': ['व्यक्तित्व', 'संगीत', 'पसंद'],
  'vyaktitva-neighbor': ['व्यक्तित्व', 'पड़ोसी', 'सामाजिक'],
  'vyaktitva-office-politics': ['व्यक्तित्व', 'ऑफिस', 'वायरल'],
  'vyaktitva-padhai': ['व्यक्तित्व', 'पढ़ाई', 'शिक्षा'],
  'vyaktitva-paisa': ['व्यक्तित्व', 'पैसा', 'वित्त'],
  'vyaktitva-parenting': ['व्यक्तित्व', 'पालन', 'परिवार'],
  'vyaktitva-parivar': ['व्यक्तित्व', 'परिवार', 'रिश्ता'],
  'vyaktitva-patience': ['व्यक्तित्व', 'धैर्य', 'मन'],
  'vyaktitva-phone': ['व्यक्तित्व', 'फोन', 'तकनीक'],
  'vyaktitva-pyaar': ['व्यक्तित्व', 'प्यार', 'रिश्ता'],
  'vyaktitva-retirement': ['व्यक्तित्व', 'रिटायरमेंट', 'जीवन'],
  'vyaktitva-risk': ['व्यक्तित्व', 'जोखिम', 'निर्णय'],
  'vyaktitva-sanskar': ['व्यक्तित्व', 'संस्कार', 'भारत'],

  // === MANO (심리) ===
  'mano-aaram': ['मनोविज्ञान', 'आराम', 'जीवन'],
  'mano-aasha': ['मनोविज्ञान', 'आशा', 'भावना'],
  'mano-aatmvishwas': ['मनोविज्ञान', 'आत्मविश्वास', 'वायरल'],
  'mano-abhilasha': ['मनोविज्ञान', 'इच्छा', 'लक्ष्य'],
  'mano-akela': ['मनोविज्ञान', 'अकेलापन', 'भावना'],
  'mano-asafalta': ['मनोविज्ञान', 'असफलता', 'भावना'],
  'mano-atmsamman': ['मनोविज्ञान', 'आत्मसम्मान', 'वायरल'],
  'mano-badlav': ['मनोविज्ञान', 'बदलाव', 'जीवन'],
  'mano-bhavna': ['मनोविज्ञान', 'भावना', 'EQ'],
  'mano-chinta': ['मनोविज्ञान', 'चिंता', 'मानसिक'],
  'mano-dar': ['मनोविज्ञान', 'डर', 'भावना'],
  'mano-daya': ['मनोविज्ञान', 'दया', 'भावना'],
  'mano-dhairya': ['मनोविज्ञान', 'धैर्य', 'मन'],
  'mano-dosti': ['मनोविज्ञान', 'दोस्ती', 'रिश्ता'],
  'mano-hal': ['मनोविज्ञान', 'समाधान', 'समस्या'],
  'mano-himmat': ['मनोविज्ञान', 'हिम्मत', 'भावना'],
  'mano-irrsha': ['मनोविज्ञान', 'ईर्ष्या', 'भावना'],
  'mano-kaam': ['मनोविज्ञान', 'काम', 'प्रेरणा'],
  'mano-khushi': ['मनोविज्ञान', 'खुशी', 'भावना'],
  'mano-krodh': ['मनोविज्ञान', 'क्रोध', 'भावना'],
  'mano-laalach': ['मनोविज्ञान', 'लालच', 'भावना'],
  'mano-lagav': ['मनोविज्ञान', 'लगाव', 'रिश्ता'],
  'mano-lakshya': ['मनोविज्ञान', 'लक्ष्य', 'प्रेरणा'],
  'mano-masti': ['मनोविज्ञान', 'मस्ती', 'खुशी'],
  'mano-neend': ['मनोविज्ञान', 'नींद', 'स्वास्थ्य'],
  'mano-netritva': ['मनोविज्ञान', 'नेतृत्व', 'करियर'],
  'mano-nirasha': ['मनोविज्ञान', 'निराशा', 'भावना'],
  'mano-nirnay': ['मनोविज्ञान', 'निर्णय', 'दिमाग'],
  'mano-paisa': ['मनोविज्ञान', 'पैसा', 'वित्त'],
  'mano-parivar': ['मनोविज्ञान', 'परिवार', 'रिश्ता'],
  'mano-pratibha': ['मनोविज्ञान', 'प्रतिभा', 'क्षमता'],
  'mano-prayas': ['मनोविज्ञान', 'प्रयास', 'प्रेरणा'],
  'mano-prem': ['मनोविज्ञान', 'प्रेम', 'भावना'],
  'mano-prerana': ['मनोविज्ञान', 'प्रेरणा', 'वायरल'],
  'mano-rachnatmak': ['मनोविज्ञान', 'रचनात्मक', 'सोच'],
  'mano-safalta': ['मनोविज्ञान', 'सफलता', 'प्रेरणा'],
  'mano-sahaj': ['मनोविज्ञान', 'सहजता', 'जीवन'],
  'mano-sahayog': ['मनोविज्ञान', 'सहयोग', 'सामाजिक'],
  'mano-samajh': ['मनोविज्ञान', 'समझ', 'EQ'],
  'mano-samasya': ['मनोविज्ञान', 'समस्या', 'समाधान'],
  'mano-samay': ['मनोविज्ञान', 'समय', 'प्रबंधन'],
  'mano-sambandh': ['मनोविज्ञान', 'संबंध', 'रिश्ता'],
  'mano-samvad': ['मनोविज्ञान', 'संवाद', 'संवाद'],
  'mano-samvedna': ['मनोविज्ञान', 'संवेदना', 'EQ'],
  'mano-sankalp': ['मनोविज्ञान', 'संकल्प', 'प्रेरणा'],
  'mano-santulan': ['मनोविज्ञान', 'संतुलन', 'जीवन'],
  'mano-santushti': ['मनोविज्ञान', 'संतुष्टि', 'खुशी'],
  'mano-shanti': ['मनोविज्ञान', 'शांति', 'मन'],
  'mano-shraddha': ['मनोविज्ञान', 'श्रद्धा', 'विश्वास'],
  'mano-soch': ['मनोविज्ञान', 'सोच', 'दिमाग'],
  'mano-sudhar': ['मनोविज्ञान', 'सुधार', 'विकास'],
  'mano-swabhiman': ['मनोविज्ञान', 'स्वाभिमान', 'भावना'],
  'mano-swikaar': ['मनोविज्ञान', 'स्वीकार', 'जीवन'],
  'mano-tanaav': ['मनोविज्ञान', 'तनाव', 'मानसिक'],
  'mano-tanav-mukti': ['मनोविज्ञान', 'तनाव', 'आराम'],
  'mano-tyag': ['मनोविज्ञान', 'त्याग', 'भावना'],
  'mano-utsah': ['मनोविज्ञान', 'उत्साह', 'प्रेरणा'],
  'mano-vichar': ['मनोविज्ञान', 'विचार', 'सोच'],
  'mano-vishwas': ['मनोविज्ञान', 'विश्वास', 'रिश्ता'],
  'mano-vyavastha': ['मनोविज्ञान', 'व्यवस्था', 'जीवन'],

  // === RISHTA (관계) ===
  'rishta-anniversary': ['रिश्ता', 'सालगिरह', 'प्यार'],
  'rishta-arranged': ['रिश्ता', 'अरेंज्ड', 'शादी'],
  'rishta-attachment': ['रिश्ता', 'लगाव', 'मनोविज्ञान'],
  'rishta-boundaries': ['रिश्ता', 'सीमाएं', 'मनोविज्ञान'],
  'rishta-breakup': ['रिश्ता', 'ब्रेकअप', 'दिल'],
  'rishta-career-balance': ['रिश्ता', 'करियर', 'संतुलन'],
  'rishta-children': ['रिश्ता', 'बच्चे', 'परिवार'],
  'rishta-commitment': ['रिश्ता', 'प्रतिबद्धता', 'प्यार'],
  'rishta-communication': ['रिश्ता', 'संवाद', 'प्यार'],
  'rishta-compatibility': ['रिश्ता', 'अनुकूलता', 'जोड़ी'],
  'rishta-conflict': ['रिश्ता', 'झगड़ा', 'समाधान'],
  'rishta-dating-style': ['रिश्ता', 'डेटिंग', 'वायरल'],
  'rishta-dosti': ['रिश्ता', 'दोस्ती', 'प्यार'],
  'rishta-expectations': ['रिश्ता', 'उम्मीदें', 'प्यार'],
  'rishta-finances': ['रिश्ता', 'पैसा', 'शादी'],
  'rishta-first-love': ['रिश्ता', 'पहला प्यार', 'वायरल'],
  'rishta-forgiveness': ['रिश्ता', 'माफी', 'प्यार'],
  'rishta-freedom': ['रिश्ता', 'आज़ादी', 'प्यार'],
  'rishta-future': ['रिश्ता', 'भविष्य', 'योजना'],
  'rishta-gifts': ['रिश्ता', 'तोहफे', 'प्यार'],
  'rishta-growth': ['रिश्ता', 'विकास', 'प्यार'],
  'rishta-honeymoon': ['रिश्ता', 'हनीमून', 'शादी'],
  'rishta-inlaws': ['रिश्ता', 'ससुराल', 'परिवार'],
  'rishta-intimacy': ['रिश्ता', 'नज़दीकी', 'प्यार'],
  'rishta-jealousy': ['रिश्ता', 'जलन', 'भावना'],
  'rishta-jhagda': ['रिश्ता', 'झगड़ा', 'संवाद'],
  'rishta-joint-family': ['रिश्ता', 'संयुक्त परिवार', 'भारत'],
  'rishta-long-distance': ['रिश्ता', 'LDR', 'प्यार'],
  'rishta-love-marriage': ['रिश्ता', 'लव मैरिज', 'वायरल'],
  'rishta-loyalty': ['रिश्ता', 'वफ़ादारी', 'प्यार'],
  'rishta-milan': ['रिश्ता', 'मिलन', 'प्यार'],
  'rishta-nuclear-family': ['रिश्ता', 'छोटा परिवार', 'जीवन'],
  'rishta-online-dating': ['रिश्ता', 'ऑनलाइन डेटिंग', 'वायरल'],
  'rishta-parivar': ['रिश्ता', 'परिवार', 'प्यार'],
  'rishta-priorities': ['रिश्ता', 'प्राथमिकता', 'प्यार'],
  'rishta-proposal': ['रिश्ता', 'प्रपोज़ल', 'वायरल'],
  'rishta-pyar': ['रिश्ता', 'प्यार', 'वायरल'],
  'rishta-quality-time': ['रिश्ता', 'समय', 'प्यार'],
  'rishta-respect': ['रिश्ता', 'सम्मान', 'प्यार'],
  'rishta-romance': ['रिश्ता', 'रोमांस', 'प्यार'],
  'rishta-saathi': ['रिश्ता', 'साथी', 'प्यार'],
  'rishta-samjhauta': ['रिश्ता', 'समझौता', 'प्यार'],
  'rishta-sasural': ['रिश्ता', 'ससुराल', 'परिवार'],
  'rishta-service': ['रिश्ता', 'सेवा', 'प्यार'],
  'rishta-shaadi': ['रिश्ता', 'शादी', 'भारत'],
  'rishta-support': ['रिश्ता', 'सहारा', 'प्यार'],
  'rishta-touch': ['रिश्ता', 'स्पर्श', 'प्यार'],
  'rishta-values': ['रिश्ता', 'मूल्य', 'संस्कार'],
  'rishta-vishwas': ['रिश्ता', 'विश्वास', 'प्यार'],
  'rishta-words': ['रिश्ता', 'शब्द', 'संवाद'],

  // === KAREER (커리어) ===
  'kareer-abroad': ['करियर', 'विदेश', 'नौकरी'],
  'kareer-boss': ['करियर', 'बॉस', 'वायरल'],
  'kareer-burnout': ['करियर', 'थकान', 'मानसिक'],
  'kareer-colleague': ['करियर', 'सहकर्मी', 'ऑफिस'],
  'kareer-communication': ['करियर', 'संवाद', 'पेशेवर'],
  'kareer-conflict': ['करियर', 'झगड़ा', 'ऑफिस'],
  'kareer-consulting': ['करियर', 'कंसल्टिंग', 'पेशा'],
  'kareer-creative': ['करियर', 'रचनात्मक', 'पेशा'],
  'kareer-deadline': ['करियर', 'डेडलाइन', 'तनाव'],
  'kareer-engineering': ['करियर', 'इंजीनियरिंग', 'पेशा'],
  'kareer-family-business': ['करियर', 'पारिवारिक व्यापार', 'व्यापार'],
  'kareer-finance': ['करियर', 'फाइनेंस', 'पेशा'],
  'kareer-freelance': ['करियर', 'फ्रीलांस', 'वायरल'],
  'kareer-goal': ['करियर', 'लक्ष्य', 'प्रेरणा'],
  'kareer-government': ['करियर', 'सरकारी', 'नौकरी'],
  'kareer-hr': ['करियर', 'HR', 'पेशा'],
  'kareer-interview': ['करियर', 'इंटरव्यू', 'वायरल'],
  'kareer-it': ['करियर', 'IT', 'तकनीक'],
  'kareer-law': ['करियर', 'कानून', 'पेशा'],
  'kareer-marketing': ['करियर', 'मार्केटिंग', 'पेशा'],
  'kareer-mba': ['करियर', 'MBA', 'शिक्षा'],
  'kareer-medical': ['करियर', 'मेडिकल', 'पेशा'],
  'kareer-mentor': ['करियर', 'मेंटर', 'मार्गदर्शन'],
  'kareer-motivation': ['करियर', 'प्रेरणा', 'वायरल'],
  'kareer-multitask': ['करियर', 'मल्टीटास्क', 'क्षमता'],
  'kareer-naukri': ['करियर', 'नौकरी', 'वायरल'],
  'kareer-netritva': ['करियर', 'नेतृत्व', 'वायरल'],
  'kareer-networking': ['करियर', 'नेटवर्किंग', 'सामाजिक'],
  'kareer-office': ['करियर', 'ऑफिस', 'काम'],
  'kareer-presentation': ['करियर', 'प्रेजेंटेशन', 'संवाद'],
  'kareer-promotion': ['करियर', 'प्रमोशन', 'वायरल'],
  'kareer-research': ['करियर', 'रिसर्च', 'शिक्षा'],
  'kareer-salary': ['करियर', 'सैलरी', 'पैसा'],
  'kareer-sales': ['करियर', 'सेल्स', 'पेशा'],
  'kareer-samay': ['करियर', 'समय', 'प्रबंधन'],
  'kareer-skills': ['करियर', 'स्किल्स', 'विकास'],
  'kareer-startup': ['करियर', 'स्टार्टअप', 'व्यापार'],
  'kareer-switch': ['करियर', 'स्विच', 'बदलाव'],
  'kareer-tanaav': ['करियर', 'तनाव', 'मानसिक'],
  'kareer-teaching': ['करियर', 'शिक्षा', 'पेशा'],
  'kareer-teamwork': ['करियर', 'टीमवर्क', 'सहयोग'],
  'kareer-vyapar': ['करियर', 'व्यापार', 'पैसा'],
  'kareer-wfh': ['करियर', 'WFH', 'वायरल'],
  'kareer-work-life': ['करियर', 'संतुलन', 'जीवन'],
  'kareer-yogyata': ['करियर', 'योग्यता', 'क्षमता'],

  // === MAZAA (재미) ===
  'mazaa-airport': ['मज़ा', 'एयरपोर्ट', 'यात्रा'],
  'mazaa-aunty': ['मज़ा', 'आंटी', 'वायरल'],
  'mazaa-baarish': ['मज़ा', 'बारिश', 'मौसम'],
  'mazaa-barber': ['मज़ा', 'बाल', 'वायरल'],
  'mazaa-bargain': ['मज़ा', 'मोलभाव', 'भारत'],
  'mazaa-beach': ['मज़ा', 'बीच', 'यात्रा'],
  'mazaa-bike': ['मज़ा', 'बाइक', 'यात्रा'],
  'mazaa-biryani': ['मज़ा', 'बिरयानी', 'खाना'],
  'mazaa-bollywood': ['मज़ा', 'बॉलीवुड', 'फिल्म'],
  'mazaa-book': ['मज़ा', 'किताब', 'पढ़ाई'],
  'mazaa-boss': ['मज़ा', 'बॉस', 'ऑफिस'],
  'mazaa-bus': ['मज़ा', 'बस', 'यात्रा'],
  'mazaa-car': ['मज़ा', 'कार', 'यात्रा'],
  'mazaa-chai': ['मज़ा', 'चाय', 'भारत'],
  'mazaa-child': ['मज़ा', 'बच्चा', 'परिवार'],
  'mazaa-chutney': ['मज़ा', 'चटनी', 'खाना'],
  'mazaa-circus': ['मज़ा', 'सर्कस', 'मनोरंजन'],
  'mazaa-city': ['मज़ा', 'शहर', 'यात्रा'],
  'mazaa-colleague': ['मज़ा', 'सहकर्मी', 'ऑफिस'],
  'mazaa-courier': ['मज़ा', 'कूरियर', 'वायरल'],
  'mazaa-cricket': ['मज़ा', 'क्रिकेट', 'खेल'],
  'mazaa-cycle': ['मज़ा', 'साइकिल', 'यात्रा'],
  'mazaa-dal': ['मज़ा', 'दाल', 'खाना'],
  'mazaa-dance': ['मज़ा', 'नाच', 'मनोरंजन'],
  'mazaa-desert': ['मज़ा', 'रेगिस्तान', 'यात्रा'],
  'mazaa-diwali': ['मज़ा', 'दिवाली', 'त्योहार'],
  'mazaa-doctor': ['मज़ा', 'डॉक्टर', 'वायरल'],
  'mazaa-dosa': ['मज़ा', 'डोसा', 'खाना'],
  'mazaa-dream': ['मज़ा', 'सपने', 'मनोरंजन'],
  'mazaa-food': ['मज़ा', 'खाना', 'भारत'],
  'mazaa-garmi': ['मज़ा', 'गर्मी', 'मौसम'],
  'mazaa-gully': ['मज़ा', 'गली', 'भारत'],
  'mazaa-gym': ['मज़ा', 'जिम', 'फिटनेस'],
  'mazaa-heroine': ['मज़ा', 'हीरोइन', 'बॉलीवुड'],
  'mazaa-hill': ['मज़ा', 'पहाड़', 'यात्रा'],
  'mazaa-holi': ['मज़ा', 'होली', 'त्योहार'],
  'mazaa-insta': ['मज़ा', 'इंस्टा', 'सोशल मीडिया'],
  'mazaa-ipl': ['मज़ा', 'IPL', 'क्रिकेट'],
  'mazaa-jog': ['मज़ा', 'जॉगिंग', 'फिटनेस'],
  'mazaa-jungle': ['मज़ा', 'जंगल', 'यात्रा'],
  'mazaa-laptop': ['मज़ा', 'लैपटॉप', 'तकनीक'],
  'mazaa-lassi': ['मज़ा', 'लस्सी', 'पीना'],
  'mazaa-mela': ['मज़ा', 'मेला', 'मनोरंजन'],
  'mazaa-metro': ['मज़ा', 'मेट्रो', 'यात्रा'],
  'mazaa-mithai': ['मज़ा', 'मिठाई', 'खाना'],
  'mazaa-mohalla': ['मज़ा', 'मोहल्ला', 'भारत'],
  'mazaa-movie-genre': ['मज़ा', 'फिल्म', 'मनोरंजन'],
  'mazaa-museum': ['मज़ा', 'संग्रहालय', 'यात्रा'],
  'mazaa-music': ['मज़ा', 'संगीत', 'मनोरंजन'],
  'mazaa-nap': ['मज़ा', 'झपकी', 'आराम'],
  'mazaa-neighbor': ['मज़ा', 'पड़ोसी', 'वायरल'],
  'mazaa-newspaper': ['मज़ा', 'अखबार', 'वायरल'],
  'mazaa-paan': ['मज़ा', 'पान', 'भारत'],
  'mazaa-paneer': ['मज़ा', 'पनीर', 'खाना'],
  'mazaa-paratha': ['मज़ा', 'पराठा', 'खाना'],
  'mazaa-parent': ['मज़ा', 'माता-पिता', 'परिवार'],
  'mazaa-park': ['मज़ा', 'पार्क', 'मनोरंजन'],
  'mazaa-parking': ['मज़ा', 'पार्किंग', 'वायरल'],
  'mazaa-pet': ['मज़ा', 'पालतू', 'प्यार'],
  'mazaa-phone': ['मज़ा', 'फोन', 'तकनीक'],
  'mazaa-pickle': ['मज़ा', 'अचार', 'खाना'],
  'mazaa-radio': ['मज़ा', 'रेडियो', 'मनोरंजन'],
  'mazaa-raita': ['मज़ा', 'रायता', 'खाना'],
  'mazaa-relative': ['मज़ा', 'रिश्तेदार', 'परिवार'],
  'mazaa-rickshaw': ['मज़ा', 'रिक्शा', 'भारत'],
  'mazaa-river': ['मज़ा', 'नदी', 'यात्रा'],
  'mazaa-roti': ['मज़ा', 'रोटी', 'खाना'],
  'mazaa-sabzi': ['मज़ा', 'सब्ज़ी', 'खाना'],
  'mazaa-samosa': ['मज़ा', 'समोसा', 'खाना'],
  'mazaa-sardi': ['मज़ा', 'सर्दी', 'मौसम'],
  'mazaa-scooter': ['मज़ा', 'स्कूटर', 'यात्रा'],
  'mazaa-shaadi': ['मज़ा', 'शादी', 'भारत'],
  'mazaa-shopkeeper': ['मज़ा', 'दुकानदार', 'वायरल'],
  'mazaa-shopping': ['मज़ा', 'शॉपिंग', 'खरीदारी'],
  'mazaa-sleep': ['मज़ा', 'नींद', 'आराम'],
  'mazaa-state': ['मज़ा', 'राज्य', 'भारत'],
  'mazaa-street-food': ['मज़ा', 'स्ट्रीट फूड', 'खाना'],
  'mazaa-student': ['मज़ा', 'छात्र', 'पढ़ाई'],
  'mazaa-supari': ['मज़ा', 'सुपारी', 'भारत'],
  'mazaa-tailor': ['मज़ा', 'दर्जी', 'वायरल'],
  'mazaa-tandoor': ['मज़ा', 'तंदूर', 'खाना'],
  'mazaa-temple': ['मज़ा', 'मंदिर', 'धर्म'],
  'mazaa-thali': ['मज़ा', 'थाली', 'खाना'],
  'mazaa-tinder': ['मज़ा', 'टिंडर', 'डेटिंग'],
  'mazaa-traffic': ['मज़ा', 'ट्रैफिक', 'वायरल'],
  'mazaa-train': ['मज़ा', 'ट्रेन', 'यात्रा'],
  'mazaa-tutor': ['मज़ा', 'ट्यूटर', 'पढ़ाई'],
  'mazaa-tv': ['मज़ा', 'TV', 'मनोरंजन'],
  'mazaa-uncle': ['मज़ा', 'अंकल', 'वायरल'],
  'mazaa-villain': ['मज़ा', 'विलेन', 'बॉलीवुड'],
  'mazaa-walk': ['मज़ा', 'चलना', 'फिटनेस'],
  'mazaa-watchman': ['मज़ा', 'वॉचमैन', 'वायरल'],
  'mazaa-whatsapp': ['मज़ा', 'व्हाट्सएप', 'सोशल मीडिया'],
  'mazaa-yoga': ['मज़ा', 'योग', 'स्वास्थ्य'],
  'mazaa-zoo': ['मज़ा', 'चिड़ियाघर', 'मनोरंजन'],

  // === BUDDHI (IQ) ===
  'buddhi-creative': ['IQ', 'रचनात्मक', 'दिमाग'],
  'buddhi-dhyan': ['IQ', 'ध्यान', 'फोकस'],
  'buddhi-emotional': ['EQ', 'भावना', 'दिमाग'],
  'buddhi-ganit': ['IQ', 'गणित', 'दिमाग'],
  'buddhi-observation': ['IQ', 'अवलोकन', 'दिमाग'],
  'buddhi-pattern': ['IQ', 'पैटर्न', 'दिमाग'],
  'buddhi-problem-solving': ['IQ', 'समस्या', 'दिमाग'],
  'buddhi-reasoning': ['IQ', 'तर्क', 'दिमाग'],
  'buddhi-samanya-gyan': ['IQ', 'सामान्य ज्ञान', 'दिमाग'],
  'buddhi-shabdawali': ['IQ', 'शब्दावली', 'भाषा'],
  'buddhi-smriti': ['IQ', 'स्मृति', 'दिमाग'],
  'buddhi-spatial': ['IQ', 'स्थानिक', 'दिमाग'],
  'buddhi-speed': ['IQ', 'गति', 'दिमाग'],
  'buddhi-tark': ['IQ', 'तर्क', 'दिमाग'],
  'buddhi-vishleshan': ['IQ', 'विश्लेषण', 'दिमाग'],
};

// Default tags by category
const defaultCategoryTags: Record<string, string[]> = {
  personality: ['व्यक्तित्व', 'स्वभाव', 'वायरल'],
  psychology: ['मनोविज्ञान', 'भावना', 'मन'],
  relationship: ['रिश्ता', 'प्यार', 'संबंध'],
  career: ['करियर', 'काम', 'नौकरी'],
  fun: ['मज़ा', 'मनोरंजन', 'वायरल'],
  iq: ['बुद्धि', 'दिमाग', 'IQ'],
};

function getTagsForSlug(slug: string, categoryId: string): string[] {
  return testTagsHi[slug] || defaultCategoryTags[categoryId] || ['मज़ा', 'मनोरंजन', 'वायरल'];
}

// Generate test entries
function generateTestEntry(slug: string, categoryId: string): TestHi {
  const title = hindiTitles[slug] || formatTitle(slug);
  const isIq = categoryId === 'iq';
  
  return {
    id: slug,
    title: title,
    slug: slug,
    description: `${categoryDescriptions[categoryId] || 'यह टेस्ट लें और जानें'}। ${title} के बारे में जानें!`,
    shortDescription: `${title} जानें`,
    categoryId: categoryId,
    thumbnailUrl: `/images/tests/${slug}.png`,
    questionCount: isIq ? 15 : 12,
    estimatedTime: isIq ? 5 : 3,
    participantCount: 15000 + Math.floor(Math.random() * 50000),
    tags: getTagsForSlug(slug, categoryId),
    createdAt: '2024-12-05',
  };
}

// Generate all tests
export const testsHi: TestHi[] = [
  // Personality tests (vyaktitva-) - 50
  ...vyaktitvaTests.map(slug => generateTestEntry(slug, 'personality')),
  // Psychology tests (mano-) - 60
  ...manoTests.map(slug => generateTestEntry(slug, 'psychology')),
  // Relationship tests (rishta-) - 50
  ...rishtaTests.map(slug => generateTestEntry(slug, 'relationship')),
  // Career tests (kareer-) - 45
  ...kareerTests.map(slug => generateTestEntry(slug, 'career')),
  // Fun tests (mazaa-) - 95
  ...mazaaTests.map(slug => generateTestEntry(slug, 'fun')),
  // IQ tests (buddhi-) - 15
  ...buddhiTests.map(slug => generateTestEntry(slug, 'iq')),
];

// Helper functions
export function getTestBySlugHi(slug: string): TestHi | undefined {
  return testsHi.find(test => test.slug === slug);
}

export function getTestsByCategoryHi(categoryId: string): TestHi[] {
  return testsHi.filter(test => test.categoryId === categoryId);
}

export function getCategoryByIdHi(categoryId: string): CategoryHi | undefined {
  return categoriesHi.find(category => category.id === categoryId);
}

// Export test counts for verification
export const testCountsHi = {
  personality: vyaktitvaTests.length,
  psychology: manoTests.length,
  relationship: rishtaTests.length,
  career: kareerTests.length,
  fun: mazaaTests.length,
  iq: buddhiTests.length,
  total: testsHi.length,
};
